import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const V="similarity-v9.7",H=[7,30,90],K=40,MIN=15;
function key(){const x=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(x)return x;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||null}catch{return null}}
async function all(q:any){const o:any[]=[];for(let f=0;;f+=1000){const{data,error}=await q().range(f,f+999);if(error)throw error;o.push(...(data||[]));if(!data||data.length<1000)break}return o}
const n=(x:any)=>x==null?null:Number(x),fin=(x:any):x is number=>Number.isFinite(x);
function med(a:number[]){a=a.filter(fin).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function qt(a:number[],p:number){a=a.filter(fin).sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?a[l]:a[l]+(a[h]-a[l])*(i-l)}
function sum(z:any[]){const ar=z.map(x=>n(x.asset_return_pct)).filter(fin),br=z.map(x=>n(x.btc_relative_return_pct)).filter(fin),mfe=z.map(x=>n(x.max_favorable_excursion_pct)).filter(fin),dd=z.map(x=>n(x.max_drawdown_pct)).filter(fin);return{n:z.length,median_return_pct:med(ar),q25_return_pct:qt(ar,.25),q75_return_pct:qt(ar,.75),median_btc_relative_pct:med(br),median_mfe_pct:med(mfe),median_max_drawdown_pct:med(dd),positive_rate_pct:ar.length?100*ar.filter(x=>x>0).length/ar.length:null}}
function vec(x:any){return{return_7d:n(x.return_7d),return_30d:n(x.return_30d),rsi_14:n(x.rsi_14),price_vs_ma50_pct:n(x.price_vs_ma50_pct),price_vs_ma200_pct:n(x.price_vs_ma200_pct),drawdown_90d_pct:n(x.drawdown_90d_pct),btc_relative_30d:n(x.btc_relative_30d)}}
const S:any={return_7d:12,return_30d:25,rsi_14:20,price_vs_ma50_pct:18,price_vs_ma200_pct:30,drawdown_90d_pct:25,btc_relative_30d:20};
function dist(a:any,b:any){let s=0,w=0;for(const k of Object.keys(S)){const x=n(a[k]),y=n(b[k]);if(x==null||y==null)continue;const d=(x-y)/S[k];s+=d*d;w++}return w>=5?Math.sqrt(s/w):null}
const DAY=86400000,date=(t:number)=>new Date(t).toISOString().slice(0,10),dms=(d:string)=>Date.parse(d+"T00:00:00Z");
// Replay observations stop 90 days before the latest price (they need matured outcomes), so the newest one is NOT today.
// Today's vector is computed from persisted Coinbase closes with the same formulas as historical-replay.
function sma(xs:any[],k:number){if(xs.length<k)return null;return xs.slice(-k).reduce((s,x)=>s+x.p,0)/k}
function rsi(rows:any[],k=14){if(rows.length<k+1)return null;const x=rows.slice(-(k+1));let up=0,dn=0;for(let i=1;i<x.length;i++){const d=x[i].p-x[i-1].p;if(d>0)up+=d;else dn-=d}if(dn===0)return 100;const rs=(up/k)/(dn/k);return 100-100/(1+rs)}
function trend(p:number,m50:any,m200:any){if(m50==null||m200==null)return"INSUFFICIENT";if(p>=m50&&p>=m200)return"ABOVE_50_200";if(p>=m50)return"ABOVE_50_ONLY";if(p>=m200)return"ABOVE_200_ONLY";return"BELOW_50_200"}
function nearest(rows:any[],t:number,gap:number){let b:any=null,g=Infinity;for(const x of rows){const d=Math.abs(x.t-t);if(d<g){g=d;b=x}}return g<=gap?b:null}
function ret(rows:any[],t:number,d:number,p:number){const x=nearest(rows,t-d*DAY,3*DAY);return x?.p>0?(p/x.p-1)*100:null}
function dd90(rows:any[],p:number){const x=rows.slice(-90);if(!x.length)return null;const hi=Math.max(...x.map(z=>z.p));return hi>0?(p/hi-1)*100:null}
function today(px:any[],btc:any[]){if(px.length<60)return null;const x=px[px.length-1];if(Date.now()-x.t>4*DAY)return null;const m50=sma(px,50),m200=sma(px,200),b=nearest(btc,x.t,2*DAY),r30=ret(px,x.t,30,x.p),br30=b?ret(btc,x.t,30,b.p):null;
 return{as_of:date(x.t),price:x.p,return_7d:ret(px,x.t,7,x.p),return_30d:r30,rsi_14:rsi(px),price_vs_ma50_pct:m50?(x.p/m50-1)*100:null,price_vs_ma200_pct:m200?(x.p/m200-1)*100:null,drawdown_90d_pct:dd90(px,x.p),btc_relative_30d:r30!=null&&br30!=null?r30-br30:null,trend_state:trend(x.p,m50,m200)}}
async function btcDaily(){const o=new Map<number,number>(),end=Date.now();for(let st=end-260*DAY;st<end;st+=250*DAY){const u=new URL("https://api.exchange.coinbase.com/products/BTC-USD/candles");u.searchParams.set("granularity","86400");u.searchParams.set("start",new Date(st).toISOString());u.searchParams.set("end",new Date(Math.min(end,st+250*DAY)).toISOString());const r=await fetch(u,{headers:{accept:"application/json","user-agent":"crypto-asymmetry-engine"}});if(!r.ok)throw Error(`Coinbase BTC-USD candles ${r.status}`);for(const c of await r.json()){const t=Number(c?.[0])*1000,p=Number(c?.[4]);if(Number.isFinite(t)&&p>0)o.set(t,p)}}return[...o].map(([t,p])=>({t,p})).sort((x,y)=>x.t-y.t)}
function state(s:any){if(!s||s.n<MIN)return"INSUFFICIENT_EVIDENCE";const r=n(s.median_return_pct),b=n(s.median_btc_relative_pct);if(r!=null&&b!=null&&r>=5&&b>=0)return"SUPPORTIVE";if(r!=null&&b!=null&&r<=-5&&b<=0)return"CAUTIONARY";return"MIXED"}
function conf(k:number,d:any){if(k<MIN)return"INSUFFICIENT";if(k>=30&&d!=null&&d<=.75)return"MODERATE";return"LOW"}
Deno.serve(async req=>{try{const sec=Deno.env.get("MONITOR_CRON_SECRET")||"";if(!sec||req.headers.get("x-monitor-secret")!==sec)return Response.json({error:"unauthorized"},{status:401});const url=Deno.env.get("SUPABASE_URL"),sk=key();if(!url||!sk)throw Error("Supabase credentials unavailable");const db=createClient(url,sk,{auth:{persistSession:false}});
const [assets,obs,outs]=await Promise.all([all(()=>db.from("research_assets").select("id,user_id,symbol,stage").neq("stage","archived").order("id")),all(()=>db.from("historical_replay_observations").select("*").order("observed_date")),all(()=>db.from("historical_replay_outcomes").select("*").order("id"))]);
const om=new Map<number,any[]>();for(const o of outs){if(!om.has(o.replay_observation_id))om.set(o.replay_observation_id,[]);om.get(o.replay_observation_id)!.push(o)}let written=0,errors:any[]=[];const btc=await btcDaily().catch(e=>{console.error(String(e));return[] as any[]}),since=date(Date.now()-260*DAY);
for(const a of assets){try{let r=obs.filter((x:any)=>x.user_id===a.user_id&&x.research_asset_id===a.id),multi=r.some((x:any)=>x.replay_version==="replay-v9.3.1-multiyear");r=r.filter((x:any)=>x.replay_version===(multi?"replay-v9.3.1-multiyear":"replay-v9.2"));if(r.length<2)continue;
 const px=(await all(()=>db.from("historical_price_daily").select("price_date,price").eq("user_id",a.user_id).eq("research_asset_id",a.id).eq("source","coinbase_exchange").gte("price_date",since).order("price_date"))).map((x:any)=>({t:dms(x.price_date),p:Number(x.price)})).filter((x:any)=>Number.isFinite(x.t)&&x.p>0);
 const cur=today(px,btc);if(!cur){errors.push({symbol:a.symbol,error:"no fresh Coinbase price history for today's state"});continue}
 const cv=vec(cur),asOf=dms(cur.as_of),rank=r.map((x:any)=>({x,d:dist(cv,vec(x))})).filter(q=>q.d!=null).sort((x,y)=>x.d!-y.d!);const horizons:any={};
for(const h of H){const c=rank.map(q=>({q,o:(om.get(q.x.id)||[]).find((o:any)=>o.horizon_days===h)})).filter(x=>x.o&&dms(x.q.x.observed_date)+h*DAY<=asOf).slice(0,K),z=sum(c.map(x=>x.o)),md=med(c.map(x=>x.q.d as number));horizons[h]={...z,state:state(z),confidence:conf(z.n,md),median_distance:md,neighbors:c.slice(0,10).map(x=>({observed_date:x.q.x.observed_date,distance:x.q.d,outcome_return_pct:x.o.asset_return_pct,outcome_btc_relative_pct:x.o.btc_relative_return_pct}))}}
let tested=0,hit=0,err:number[]=[];for(const x of r.slice(-120)){const act=(om.get(x.id)||[]).find((o:any)=>o.horizon_days===30);if(!act)continue;const p=r.filter((y:any)=>dms(y.observed_date)+30*DAY<=dms(x.observed_date)).map((y:any)=>({y,d:dist(vec(x),vec(y))})).filter(q=>q.d!=null).sort((u,v)=>u.d!-v.d!).map(q=>({q,o:(om.get(q.y.id)||[]).find((o:any)=>o.horizon_days===30)})).filter(q=>q.o).slice(0,K);if(p.length<MIN)continue;const pred=med(p.map(q=>n(q.o.asset_return_pct)).filter(fin)),actual=n(act.asset_return_pct);if(pred==null||actual==null)continue;tested++;if((pred>=0)===(actual>=0))hit++;err.push(Math.abs(pred-actual))}
const validation={horizon_days:30,samples:tested,directional_agreement_pct:tested?100*hit/tested:null,median_absolute_error_pct:med(err),method:"walk-forward; each anchor only uses neighbors whose 30D outcome had matured by the anchor date; diagnostic only"};
const row={user_id:a.user_id,research_asset_id:a.id,current_features:{as_of:cur.as_of,price:cur.price,...cv,trend_state:cur.trend_state},horizons,validation,engine_version:V};const{error}=await db.from("similarity_expectations").upsert(row,{onConflict:"user_id,research_asset_id,observed_date,engine_version"});if(error)throw error;written++}catch(e){errors.push({symbol:a.symbol,error:String(e).slice(0,180)})}}
return Response.json({ok:true,version:V,written,errors,note:"Point-in-time price/BTC similarity only; no historical fundamentals/regime/AI reconstruction."})}catch(e){return Response.json({ok:false,error:String(e)},{status:500})}})
