import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const V="similarity-v9.7",H=[7,30,90],K=40,MIN=15;
function key(){const x=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(x)return x;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||null}catch{return null}}
async function all(q:any){const o:any[]=[];for(let f=0;;f+=1000){const{data,error}=await q().range(f,f+999);if(error)throw error;o.push(...(data||[]));if(!data||data.length<1000)break}return o}
const n=(x:any)=>x==null?null:Number(x),fin=(x:any):x is number=>Number.isFinite(x);
function med(a:number[]){a=a.filter(fin).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function qt(a:number[],p:number){a=a.filter(fin).sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?a[l]:a[l]+(a[h]-a[l])*(i-l)}
function sum(z:any[]){const ar=z.map(x=>n(x.asset_return_pct)).filter(fin),br=z.map(x=>n(x.btc_relative_return_pct)).filter(fin),mfe=z.map(x=>n(x.max_favorable_excursion_pct)).filter(fin),dd=z.map(x=>n(x.max_drawdown_pct)).filter(fin);return{n:z.length,median_return_pct:med(ar),q25_return_pct:qt(ar,.25),q75_return_pct:qt(ar,.75),median_btc_relative_pct:med(br),median_mfe_pct:med(mfe),median_max_drawdown_pct:med(dd),positive_rate_pct:ar.length?100*ar.filter(x=>x>0).length/ar.length:null}}
function vec(x:any){return{return_7d:n(x.return_7d),return_30d:n(x.return_30d),rsi_14:n(x.rsi_14),price_vs_ma50_pct:n(x.price_vs_ma50_pct),price_vs_ma200_pct:n(x.price_vs_ma200_pct),drawdown_90d_pct:n(x.drawdown_90d_pct),btc_relative_30d:n(x.btc_relative_30d)}}
const S:any={return_7d:12,return_30d:25,rsi_14:20,price_vs_ma50_pct:18,price_vs_ma200_pct:30,drawdown_90d_pct:25,btc_relative_30d:20};
function dist(a:any,b:any){let s=0,w=0;for(const k of Object.keys(S)){const x=n(a[k]),y=n(b[k]);if(x==null||y==null)continue;const d=(x-y)/S[k];s+=d*d;w++}return w>=5?Math.sqrt(s/w):null}
function state(s:any){if(!s||s.n<MIN)return"INSUFFICIENT_EVIDENCE";const r=n(s.median_return_pct),b=n(s.median_btc_relative_pct);if(r!=null&&b!=null&&r>=5&&b>=0)return"SUPPORTIVE";if(r!=null&&b!=null&&r<=-5&&b<=0)return"CAUTIONARY";return"MIXED"}
function conf(k:number,d:any){if(k<MIN)return"INSUFFICIENT";if(k>=30&&d!=null&&d<=.75)return"MODERATE";return"LOW"}
Deno.serve(async req=>{try{const sec=Deno.env.get("MONITOR_CRON_SECRET")||"";if(!sec||req.headers.get("x-monitor-secret")!==sec)return Response.json({error:"unauthorized"},{status:401});const url=Deno.env.get("SUPABASE_URL"),sk=key();if(!url||!sk)throw Error("Supabase credentials unavailable");const db=createClient(url,sk,{auth:{persistSession:false}});
const [assets,obs,outs]=await Promise.all([all(()=>db.from("research_assets").select("id,user_id,symbol,stage").neq("stage","archived").order("id")),all(()=>db.from("historical_replay_observations").select("*").order("observed_date")),all(()=>db.from("historical_replay_outcomes").select("*").order("id"))]);
const om=new Map<number,any[]>();for(const o of outs){if(!om.has(o.replay_observation_id))om.set(o.replay_observation_id,[]);om.get(o.replay_observation_id)!.push(o)}let written=0,errors:any[]=[];
for(const a of assets){try{let r=obs.filter((x:any)=>x.user_id===a.user_id&&x.research_asset_id===a.id),multi=r.some((x:any)=>x.replay_version==="replay-v9.3.1-multiyear");r=r.filter((x:any)=>x.replay_version===(multi?"replay-v9.3.1-multiyear":"replay-v9.2"));if(r.length<2)continue;const cur=r[r.length-1],cv=vec(cur),rank=r.slice(0,-1).map((x:any)=>({x,d:dist(cv,vec(x))})).filter(q=>q.d!=null).sort((x,y)=>x.d!-y.d!);const horizons:any={};
for(const h of H){const c=rank.map(q=>({q,o:(om.get(q.x.id)||[]).find((o:any)=>o.horizon_days===h)})).filter(x=>x.o).slice(0,K),z=sum(c.map(x=>x.o)),md=med(c.map(x=>x.q.d as number));horizons[h]={...z,state:state(z),confidence:conf(z.n,md),median_distance:md,neighbors:c.slice(0,10).map(x=>({observed_date:x.q.x.observed_date,distance:x.q.d,outcome_return_pct:x.o.asset_return_pct,outcome_btc_relative_pct:x.o.btc_relative_return_pct}))}}
let tested=0,hit=0,err:number[]=[];for(const x of r.slice(-120)){const act=(om.get(x.id)||[]).find((o:any)=>o.horizon_days===30);if(!act)continue;const p=r.filter((y:any)=>y.observed_date<x.observed_date).map((y:any)=>({y,d:dist(vec(x),vec(y))})).filter(q=>q.d!=null).sort((u,v)=>u.d!-v.d!).map(q=>({q,o:(om.get(q.y.id)||[]).find((o:any)=>o.horizon_days===30)})).filter(q=>q.o).slice(0,K);if(p.length<MIN)continue;const pred=med(p.map(q=>n(q.o.asset_return_pct)).filter(fin)),actual=n(act.asset_return_pct);if(pred==null||actual==null)continue;tested++;if((pred>=0)===(actual>=0))hit++;err.push(Math.abs(pred-actual))}
const validation={horizon_days:30,samples:tested,directional_agreement_pct:tested?100*hit/tested:null,median_absolute_error_pct:med(err),method:"walk-forward; neighbors strictly precede each anchor; diagnostic only"};
const row={user_id:a.user_id,research_asset_id:a.id,current_features:{as_of:cur.observed_date,...cv,trend_state:cur.trend_state},horizons,validation,engine_version:V};const{error}=await db.from("similarity_expectations").upsert(row,{onConflict:"user_id,research_asset_id,observed_date,engine_version"});if(error)throw error;written++}catch(e){errors.push({symbol:a.symbol,error:String(e).slice(0,180)})}}
return Response.json({ok:true,version:V,written,errors,note:"Point-in-time price/BTC similarity only; no historical fundamentals/regime/AI reconstruction."})}catch(e){return Response.json({ok:false,error:String(e)},{status:500})}})
