-- Crypto Asymmetry Engine v6.3
-- Run in Supabase SQL editor. Requires Supabase Auth users.
create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  buy_price numeric, take_profit numeric, stop_loss numeric,
  max_fdv_tvl numeric, fee_drop numeric, amount numeric, entry_price numeric,
  entry_fees_30d numeric, is_owned boolean not null default false, notes text, updated_at timestamptz not null default now(),
  unique(user_id,symbol)
);
create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null, captured_at timestamptz not null default now(),
  price numeric, market_cap numeric, fdv numeric, tvl numeric,
  fees_30d numeric, fees_7d numeric, revenue_30d numeric, revenue_7d numeric, circulating numeric,
  total_supply numeric, max_supply numeric
);
create index if not exists snapshots_user_symbol_time on public.snapshots(user_id,symbol,captured_at desc);

alter table public.plans enable row level security;
alter table public.snapshots enable row level security;

drop policy if exists "plans_select_own" on public.plans;
drop policy if exists "plans_insert_own" on public.plans;
drop policy if exists "plans_update_own" on public.plans;
drop policy if exists "plans_delete_own" on public.plans;
create policy "plans_select_own" on public.plans for select using (auth.uid() = user_id);
create policy "plans_insert_own" on public.plans for insert with check (auth.uid() = user_id);
create policy "plans_update_own" on public.plans for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "plans_delete_own" on public.plans for delete using (auth.uid() = user_id);

drop policy if exists "snapshots_select_own" on public.snapshots;
drop policy if exists "snapshots_insert_own" on public.snapshots;
drop policy if exists "snapshots_delete_own" on public.snapshots;
create policy "snapshots_select_own" on public.snapshots for select using (auth.uid() = user_id);
create policy "snapshots_insert_own" on public.snapshots for insert with check (auth.uid() = user_id);
create policy "snapshots_delete_own" on public.snapshots for delete using (auth.uid() = user_id);

revoke all on public.plans from anon;
revoke all on public.snapshots from anon;
grant select,insert,update,delete on public.plans to authenticated;
grant select,insert,delete on public.snapshots to authenticated;


-- v5.7 snapshot retention
-- Keep only the newest 180 snapshots for each user/symbol in the cloud.
-- This runs inside Postgres after every inserted snapshot, so retention does not
-- depend on the browser being open and cannot accidentally prune another user.
create or replace function public.prune_snapshot_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.snapshots
  where id in (
    select id
    from public.snapshots
    where user_id = new.user_id
      and symbol = new.symbol
    order by captured_at desc, id desc
    offset 180
  );
  return new;
end;
$$;

revoke all on function public.prune_snapshot_history() from public;
revoke all on function public.prune_snapshot_history() from anon;
revoke all on function public.prune_snapshot_history() from authenticated;

drop trigger if exists snapshots_prune_after_insert on public.snapshots;
create trigger snapshots_prune_after_insert
after insert on public.snapshots
for each row execute function public.prune_snapshot_history();

-- v5.8 background monitoring event ledger
create table if not exists public.monitor_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  rule_type text not null,
  is_active boolean not null default false,
  last_value numeric,
  threshold numeric,
  checked_at timestamptz not null default now(),
  primary key (user_id, symbol, rule_type)
);

create table if not exists public.monitor_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  rule_type text not null,
  title text not null,
  details text,
  observed_value numeric,
  threshold numeric,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists monitor_events_user_time on public.monitor_events(user_id,created_at desc);
create index if not exists monitor_events_user_active on public.monitor_events(user_id,resolved_at,created_at desc);

alter table public.monitor_state enable row level security;
alter table public.monitor_events enable row level security;

drop policy if exists "monitor_events_select_own" on public.monitor_events;
create policy "monitor_events_select_own" on public.monitor_events for select using (auth.uid() = user_id);

-- monitor_state is server-worker-only. Users do not need direct table access.
revoke all on public.monitor_state from anon, authenticated;
revoke all on public.monitor_events from anon;
grant select on public.monitor_events to authenticated;

-- v5.9 requires no schema migration. Existing monitor_state and monitor_events tables are reused.

-- v6.0 What Changed is computed from existing snapshots and requires no schema migration.

-- v6.1 daily snapshots reuse the existing snapshots table; no schema migration is required.

-- v6.2 Decision Radar is frontend-derived from existing data; no schema migration required.

-- v6.3 additive migration for existing deployments.
alter table public.plans add column if not exists is_owned boolean not null default false;
alter table public.snapshots add column if not exists fees_7d numeric;
alter table public.snapshots add column if not exists revenue_7d numeric;


-- v8 persistent research pipeline
create table if not exists public.research_assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  coingecko_id text not null,
  name text not null,
  stage text not null default 'research' check (stage in ('research','watch','archived')),
  is_owned boolean not null default false,
  amount numeric,
  entry_price numeric,
  thesis text,
  thesis_break text,
  promoted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,coingecko_id)
);

create table if not exists public.research_evaluations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  evaluated_at timestamptz not null default now(),
  evidence_score numeric,
  evidence_coverage numeric,
  price numeric,
  return_7d numeric,
  return_30d numeric,
  fees_7d_change numeric,
  tvl_7d_change numeric,
  dilution numeric,
  status text not null,
  reason text
);
create index if not exists research_assets_user_stage on public.research_assets(user_id,stage,updated_at desc);
create index if not exists research_evaluations_asset_time on public.research_evaluations(research_asset_id,evaluated_at desc);

alter table public.research_assets enable row level security;
alter table public.research_evaluations enable row level security;

drop policy if exists "research_assets_select_own" on public.research_assets;
drop policy if exists "research_assets_insert_own" on public.research_assets;
drop policy if exists "research_assets_update_own" on public.research_assets;
drop policy if exists "research_assets_delete_own" on public.research_assets;
create policy "research_assets_select_own" on public.research_assets for select using (auth.uid()=user_id);
create policy "research_assets_insert_own" on public.research_assets for insert with check (auth.uid()=user_id);
create policy "research_assets_update_own" on public.research_assets for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "research_assets_delete_own" on public.research_assets for delete using (auth.uid()=user_id);

drop policy if exists "research_evaluations_select_own" on public.research_evaluations;
create policy "research_evaluations_select_own" on public.research_evaluations for select using (auth.uid()=user_id);

revoke all on public.research_assets from anon;
revoke all on public.research_evaluations from anon;
grant select,insert,update,delete on public.research_assets to authenticated;
grant select on public.research_evaluations to authenticated;


-- v8.2 dynamic research detail metrics (additive, safe to re-run)
alter table public.research_evaluations add column if not exists market_cap numeric;
alter table public.research_evaluations add column if not exists fdv numeric;
alter table public.research_evaluations add column if not exists volume_24h numeric;
alter table public.research_evaluations add column if not exists tvl numeric;
alter table public.research_evaluations add column if not exists fees_30d numeric;


-- v8.3 deeper dynamic-research notes (additive, safe to re-run)
alter table public.research_assets add column if not exists catalysts text;
alter table public.research_assets add column if not exists value_capture text;
alter table public.research_assets add column if not exists unlock_notes text;
alter table public.research_assets add column if not exists risk_notes text;


-- v8.4 unified asset pipeline (additive, safe to re-run)
alter table public.research_assets add column if not exists research_origin text not null default 'discovery'
  check (research_origin in ('curated','discovery','manual'));


-- v8.5 unified plans (additive, safe to re-run)
alter table public.plans add column if not exists coingecko_id text;


-- v8.6 scoring semantics (additive, safe to re-run)
alter table public.research_assets
  add column if not exists thesis_strength numeric
  check (thesis_strength is null or (thesis_strength >= 0 and thesis_strength <= 100));

-- Preserve the original curated Research Snapshot as the starting longer-lived
-- Thesis Strength. Do not overwrite any score the user has already changed.
update public.research_assets
set thesis_strength = case symbol
  when 'AAVE' then 80
  when 'PENDLE' then 78
  when 'AERO' then 73
  when 'AKT' then 73
  when 'LINK' then 72
  when 'TAO' then 67
  when 'ONDO' then 62
  when 'TIA' then 58
  when 'SUI' then 58
  else thesis_strength
end
where research_origin = 'curated'
  and thesis_strength is null
  and symbol in ('AAVE','PENDLE','AERO','AKT','LINK','TAO','ONDO','TIA','SUI');


-- v8.8 automated thesis + signal validation journal (additive, safe to re-run)
alter table public.research_assets add column if not exists thesis_coverage numeric
  check (thesis_coverage is null or (thesis_coverage >= 0 and thesis_coverage <= 100));
alter table public.research_assets add column if not exists thesis_components jsonb;
alter table public.research_assets add column if not exists thesis_updated_at timestamptz;

create table if not exists public.signal_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_date date not null default current_date,
  signal_mode text not null check (signal_mode in ('entry','position')),
  signal_label text not null,
  price numeric,
  thesis_strength numeric,
  thesis_coverage numeric,
  setup_evidence numeric,
  setup_coverage numeric,
  regime_score numeric,
  price_pattern text,
  created_at timestamptz not null default now(),
  unique(user_id,research_asset_id,observed_date,signal_mode)
);
create index if not exists signal_observations_user_asset_date on public.signal_observations(user_id,research_asset_id,observed_date desc);
alter table public.signal_observations enable row level security;
drop policy if exists "signal_observations_select_own" on public.signal_observations;
drop policy if exists "signal_observations_insert_own" on public.signal_observations;
drop policy if exists "signal_observations_update_own" on public.signal_observations;
create policy "signal_observations_select_own" on public.signal_observations for select using (auth.uid()=user_id);
create policy "signal_observations_insert_own" on public.signal_observations for insert with check (auth.uid()=user_id);
create policy "signal_observations_update_own" on public.signal_observations for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
revoke all on public.signal_observations from anon;
grant select,insert,update on public.signal_observations to authenticated;

-- v8.8.1 evidence-safety cleanup requires no schema migration.


-- v8.9 observational intelligence + validation journal v2 (additive, safe to re-run)
alter table public.signal_observations add column if not exists narrative_state text;
alter table public.signal_observations add column if not exists attention_score numeric;
alter table public.signal_observations add column if not exists rotation_state text;
alter table public.signal_observations add column if not exists competitive_momentum numeric;


-- v8.9.1 Setup Evidence consistency + model provenance (additive, safe to re-run)
alter table public.research_evaluations add column if not exists scoring_version text;
alter table public.signal_observations add column if not exists setup_scoring_version text;


-- v8.9.4 position transaction ledger
create table if not exists public.position_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  symbol text not null,
  coingecko_id text not null,
  side text not null default 'buy' check (side in ('buy')),
  token_amount numeric not null check (token_amount > 0),
  price_usd numeric not null check (price_usd > 0),
  executed_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists position_transactions_user_asset_time
  on public.position_transactions(user_id,research_asset_id,executed_at desc,id desc);

alter table public.position_transactions enable row level security;
drop policy if exists "position_transactions_select_own" on public.position_transactions;
drop policy if exists "position_transactions_insert_own" on public.position_transactions;
drop policy if exists "position_transactions_update_own" on public.position_transactions;
drop policy if exists "position_transactions_delete_own" on public.position_transactions;
create policy "position_transactions_select_own" on public.position_transactions for select using (auth.uid()=user_id);
create policy "position_transactions_insert_own" on public.position_transactions for insert with check (auth.uid()=user_id);
create policy "position_transactions_update_own" on public.position_transactions for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "position_transactions_delete_own" on public.position_transactions for delete using (auth.uid()=user_id);
revoke all on public.position_transactions from anon;
grant select,insert,update,delete on public.position_transactions to authenticated;


-- v8.9.4 journal position context for later signal/outcome analysis
alter table public.signal_observations add column if not exists position_token_amount numeric;
alter table public.signal_observations add column if not exists position_average_cost numeric;
alter table public.signal_observations add column if not exists position_cost_basis numeric;
alter table public.signal_observations add column if not exists position_unrealized_pnl numeric;
alter table public.signal_observations add column if not exists position_unrealized_pnl_pct numeric;


-- v8.9.5 structural timing intelligence

alter table public.signal_observations add column if not exists structure_stage text;
alter table public.signal_observations add column if not exists weekly_breakout_confirmation text;
alter table public.signal_observations add column if not exists btc_downside_beta numeric;


-- v8.9.6 Signal Outcome Engine
-- Crypto Asymmetry Engine v8.9.6
-- Forward Signal Outcome Engine. Safe to re-run.

create table if not exists public.signal_outcomes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  signal_observation_id bigint not null references public.signal_observations(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  horizon_days integer not null check (horizon_days in (7,30,90)),
  matured_at date not null,
  entry_price numeric,
  exit_price numeric,
  asset_return_pct numeric,
  btc_return_pct numeric,
  btc_relative_return_pct numeric,
  max_favorable_excursion_pct numeric,
  max_adverse_excursion_pct numeric,
  max_drawdown_pct numeric,
  sample_days integer,
  outcome_version text not null default 'outcome-v1',
  calculated_at timestamptz not null default now(),
  unique(signal_observation_id,horizon_days)
);

create index if not exists signal_outcomes_user_asset_horizon
  on public.signal_outcomes(user_id,research_asset_id,horizon_days,matured_at desc);
create index if not exists signal_outcomes_observation
  on public.signal_outcomes(signal_observation_id,horizon_days);

alter table public.signal_outcomes enable row level security;
drop policy if exists "signal_outcomes_select_own" on public.signal_outcomes;
create policy "signal_outcomes_select_own" on public.signal_outcomes
  for select using (auth.uid()=user_id);

revoke all on public.signal_outcomes from anon, authenticated;
grant select on public.signal_outcomes to authenticated;


-- v8.9.7 server-side daily signal capture
-- Add provenance without changing the existing journal uniqueness semantics.
alter table public.signal_observations
  add column if not exists capture_source text not null default 'client_detail';

alter table public.signal_observations
  add column if not exists signal_model_version text;

create index if not exists signal_observations_capture_source_date
  on public.signal_observations(capture_source, observed_date desc);


-- Crypto Asymmetry Engine v9.0
-- AI Research Engine v1. Additive and safe to re-run.

create table if not exists public.ai_research_assessments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  model text not null,
  model_version text not null default 'ai-research-v9.0',
  stance text not null check (stance in ('CONSTRUCTIVE','MIXED','CAUTIOUS','INSUFFICIENT_EVIDENCE')),
  confidence text not null check (confidence in ('LOW','MODERATE','HIGH')),
  quant_ai_agreement text not null check (quant_ai_agreement in ('AGREES','PARTIAL','DISAGREES','NOT_ENOUGH_DATA')),
  summary text not null,
  assessment jsonb not null,
  input_snapshot jsonb not null,
  response_id text
);

create index if not exists ai_research_assessments_user_asset_time
  on public.ai_research_assessments(user_id,research_asset_id,observed_at desc);

alter table public.ai_research_assessments enable row level security;

drop policy if exists "ai_research_assessments_select_own" on public.ai_research_assessments;
drop policy if exists "ai_research_assessments_insert_own" on public.ai_research_assessments;

create policy "ai_research_assessments_select_own"
  on public.ai_research_assessments for select
  using (auth.uid()=user_id);

create policy "ai_research_assessments_insert_own"
  on public.ai_research_assessments for insert
  with check (auth.uid()=user_id);

revoke all on public.ai_research_assessments from anon;
grant select,insert on public.ai_research_assessments to authenticated;


-- Crypto Asymmetry Engine v9.1
-- Automated Qualitative Intelligence. Additive and safe to re-run.

create table if not exists public.qualitative_research (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  model text not null,
  model_version text not null default 'qualitative-v9.1',
  catalyst_state text not null,
  value_capture_state text not null,
  dilution_state text not null,
  risk_state text not null,
  summary text not null,
  intelligence jsonb not null,
  response_id text
);

create index if not exists qualitative_research_user_asset_time
  on public.qualitative_research(user_id,research_asset_id,observed_at desc);

alter table public.qualitative_research enable row level security;

drop policy if exists "qualitative_research_select_own" on public.qualitative_research;
drop policy if exists "qualitative_research_insert_own" on public.qualitative_research;

create policy "qualitative_research_select_own"
  on public.qualitative_research for select using (auth.uid()=user_id);
create policy "qualitative_research_insert_own"
  on public.qualitative_research for insert with check (auth.uid()=user_id);

revoke all on public.qualitative_research from anon;
grant select,insert on public.qualitative_research to authenticated;


-- v9.2 Historical Replay Engine
-- Quantitative, point-in-time replay only. It intentionally does NOT backfill
-- thesis, qualitative intelligence, catalysts, regime, or AI judgments.

create table if not exists public.historical_replay_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_date date not null,
  price numeric,
  return_7d numeric,
  return_30d numeric,
  ma_50 numeric,
  ma_200 numeric,
  price_vs_ma50_pct numeric,
  price_vs_ma200_pct numeric,
  rsi_14 numeric,
  drawdown_90d_pct numeric,
  btc_return_30d numeric,
  btc_relative_30d numeric,
  trend_state text check (trend_state in ('ABOVE_50_200','ABOVE_50_ONLY','ABOVE_200_ONLY','BELOW_50_200','INSUFFICIENT')),
  replay_version text not null default 'replay-v9.2',
  created_at timestamptz not null default now(),
  unique (user_id, research_asset_id, observed_date, replay_version)
);

create table if not exists public.historical_replay_outcomes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  replay_observation_id bigint not null references public.historical_replay_observations(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  horizon_days integer not null check (horizon_days in (7,30,90)),
  matured_at date not null,
  entry_price numeric not null,
  exit_price numeric not null,
  asset_return_pct numeric,
  btc_return_pct numeric,
  btc_relative_return_pct numeric,
  max_favorable_excursion_pct numeric,
  max_adverse_excursion_pct numeric,
  max_drawdown_pct numeric,
  sample_days integer,
  replay_version text not null default 'replay-v9.2',
  calculated_at timestamptz not null default now(),
  unique (replay_observation_id, horizon_days)
);

create index if not exists historical_replay_obs_user_asset_date_idx
  on public.historical_replay_observations(user_id,research_asset_id,observed_date desc);
create index if not exists historical_replay_outcomes_user_asset_horizon_idx
  on public.historical_replay_outcomes(user_id,research_asset_id,horizon_days);

alter table public.historical_replay_observations enable row level security;
alter table public.historical_replay_outcomes enable row level security;

drop policy if exists "replay observations own select" on public.historical_replay_observations;
create policy "replay observations own select" on public.historical_replay_observations
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "replay outcomes own select" on public.historical_replay_outcomes;
create policy "replay outcomes own select" on public.historical_replay_outcomes
  for select to authenticated using (auth.uid() = user_id);

revoke all on public.historical_replay_observations from anon;
revoke all on public.historical_replay_outcomes from anon;
grant select on public.historical_replay_observations to authenticated;
grant select on public.historical_replay_outcomes to authenticated;


-- v9.3 additive calibration + multi-year provenance
create table if not exists public.historical_price_daily (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint not null references public.research_assets(id) on delete cascade,price_date date not null,
 price numeric not null check(price>0),source text not null,source_symbol text,created_at timestamptz not null default now(),
 unique(user_id,research_asset_id,price_date,source));
create index if not exists historical_price_daily_asset_date_idx on public.historical_price_daily(user_id,research_asset_id,price_date);
create table if not exists public.calibration_results (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint references public.research_assets(id) on delete cascade,scope text not null check(scope in('asset','cross_asset')),
 cohort_key text not null,cohort_label text not null,horizon_days integer not null check(horizon_days in(7,30,90)),
 sample_count integer not null,asset_count integer not null default 1,median_return_pct numeric,median_btc_relative_pct numeric,
 median_mfe_pct numeric,median_mae_pct numeric,median_max_drawdown_pct numeric,positive_rate_pct numeric,
 btc_outperformance_rate_pct numeric,q25_return_pct numeric,q75_return_pct numeric,
 confidence_state text not null check(confidence_state in('INSUFFICIENT','LOW','MODERATE','STRONGER')),
 calibration_version text not null default 'calibration-v9.3',calculated_at timestamptz not null default now(),
 unique nulls not distinct(user_id,research_asset_id,scope,cohort_key,horizon_days,calibration_version));
-- Cross-asset rows have research_asset_id NULL. A plain unique treats NULLs as distinct, so every run would insert
-- new cross-asset rows instead of updating them. This index also covers a table created from the original v9.3 SQL.
create unique index if not exists calibration_results_nnd_uniq on public.calibration_results(user_id,research_asset_id,scope,cohort_key,horizon_days,calibration_version) nulls not distinct;
create index if not exists calibration_results_user_asset_idx on public.calibration_results(user_id,research_asset_id,horizon_days);
alter table public.historical_price_daily enable row level security;alter table public.calibration_results enable row level security;
drop policy if exists "historical prices own select" on public.historical_price_daily;
create policy "historical prices own select" on public.historical_price_daily for select to authenticated using(auth.uid()=user_id);
drop policy if exists "calibration own select" on public.calibration_results;
create policy "calibration own select" on public.calibration_results for select to authenticated using(auth.uid()=user_id);
revoke all on public.historical_price_daily from anon;revoke all on public.calibration_results from anon;
grant select on public.historical_price_daily to authenticated;grant select on public.calibration_results to authenticated;


-- v9.3.1 verified market-history mapping + import provenance
alter table public.research_assets add column if not exists coinbase_product_id text;
alter table public.research_assets add column if not exists history_provider text
  check (history_provider is null or history_provider in ('coinbase','coingecko_paid','coingecko_demo'));
alter table public.research_assets add column if not exists history_verified_at timestamptz;

alter table public.historical_price_daily add column if not exists open numeric;
alter table public.historical_price_daily add column if not exists high numeric;
alter table public.historical_price_daily add column if not exists low numeric;
alter table public.historical_price_daily add column if not exists volume numeric;
alter table public.historical_price_daily add column if not exists imported_at timestamptz not null default now();

create index if not exists research_assets_coinbase_product_idx on public.research_assets(coinbase_product_id);


-- v9.3.2 Dynamic History Onboarding
-- No hardcoded research symbols. Safe to re-run.

alter table public.research_assets add column if not exists history_mapping_status text
  check (history_mapping_status is null or history_mapping_status in
    ('PENDING','VERIFIED','UNRESOLVED','AMBIGUOUS','NO_USD_PRODUCT','ERROR'));
alter table public.research_assets add column if not exists history_mapping_note text;
alter table public.research_assets add column if not exists history_last_attempt_at timestamptz;

-- Existing explicitly verified v9.3.1 mappings remain trusted.
update public.research_assets
set history_mapping_status='VERIFIED'
where coinbase_product_id is not null
  and history_mapping_status is null;

create index if not exists research_assets_history_mapping_status_idx
  on public.research_assets(history_mapping_status,stage);


-- v9.5 AI assessment live outcomes
create table if not exists public.ai_assessment_outcomes (
id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
ai_assessment_id bigint not null references public.ai_research_assessments(id) on delete cascade,
research_asset_id bigint not null references public.research_assets(id) on delete cascade,
horizon_days integer not null check (horizon_days in (7,30,90)),matured_at date not null,entry_price numeric,exit_price numeric,
asset_return_pct numeric,btc_return_pct numeric,btc_relative_return_pct numeric,max_favorable_excursion_pct numeric,
max_adverse_excursion_pct numeric,max_drawdown_pct numeric,sample_days integer,outcome_version text not null default 'ai-outcome-v9.5',
calculated_at timestamptz not null default now(),unique(ai_assessment_id,horizon_days));
create index if not exists ai_assessment_outcomes_user_asset_horizon on public.ai_assessment_outcomes(user_id,research_asset_id,horizon_days,matured_at desc);
alter table public.ai_assessment_outcomes enable row level security;
drop policy if exists "ai_assessment_outcomes_select_own" on public.ai_assessment_outcomes;
create policy "ai_assessment_outcomes_select_own" on public.ai_assessment_outcomes for select using (auth.uid()=user_id);
revoke all on public.ai_assessment_outcomes from anon,authenticated; grant select on public.ai_assessment_outcomes to authenticated;


-- v9.6 Decision & Expectation Engine
create table if not exists public.decision_expectations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  observed_date date not null default current_date,
  mode text not null check (mode in ('entry','position')),
  posture text not null,
  confidence text not null check (confidence in ('LOW','MODERATE','HIGH')),
  summary text not null,
  expectation jsonb not null,
  input_snapshot jsonb not null,
  engine_version text not null default 'decision-v9.6',
  unique(user_id,research_asset_id,observed_date,mode)
);
create index if not exists decision_expectations_user_asset_time
  on public.decision_expectations(user_id,research_asset_id,observed_at desc);
alter table public.decision_expectations enable row level security;
drop policy if exists "decision_expectations_select_own" on public.decision_expectations;
create policy "decision_expectations_select_own" on public.decision_expectations
  for select using (auth.uid()=user_id);
revoke all on public.decision_expectations from anon,authenticated;
grant select on public.decision_expectations to authenticated;
