-- Crypto Asymmetry Engine v5.7
-- Run in Supabase SQL editor. Requires Supabase Auth users.
create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  buy_price numeric, take_profit numeric, stop_loss numeric,
  max_fdv_tvl numeric, fee_drop numeric, amount numeric, entry_price numeric,
  entry_fees_30d numeric, notes text, updated_at timestamptz not null default now(),
  unique(user_id,symbol)
);
create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null, captured_at timestamptz not null default now(),
  price numeric, market_cap numeric, fdv numeric, tvl numeric,
  fees_30d numeric, revenue_30d numeric, circulating numeric,
  total_supply numeric, max_supply numeric
);
create index if not exists snapshots_user_symbol_time on public.snapshots(user_id,symbol,captured_at desc);

alter table public.plans enable row level security;
alter table public.snapshots enable row level security;

drop policy if exists "plans_select_own" on public.plans;
drop policy if exists "plans_insert_own" on public.plans;
drop policy if exists "plans_update_own" on public.plans;
drop policy if exists "plans_delete_own" on public.plans;
create policy "plans_select_own" on public.plans for select using (auth.uid() = user_id);
create policy "plans_insert_own" on public.plans for insert with check (auth.uid() = user_id);
create policy "plans_update_own" on public.plans for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "plans_delete_own" on public.plans for delete using (auth.uid() = user_id);

drop policy if exists "snapshots_select_own" on public.snapshots;
drop policy if exists "snapshots_insert_own" on public.snapshots;
drop policy if exists "snapshots_delete_own" on public.snapshots;
create policy "snapshots_select_own" on public.snapshots for select using (auth.uid() = user_id);
create policy "snapshots_insert_own" on public.snapshots for insert with check (auth.uid() = user_id);
create policy "snapshots_delete_own" on public.snapshots for delete using (auth.uid() = user_id);

revoke all on public.plans from anon;
revoke all on public.snapshots from anon;
grant select,insert,update,delete on public.plans to authenticated;
grant select,insert,delete on public.snapshots to authenticated;


-- v5.7 snapshot retention
-- Keep only the newest 180 snapshots for each user/symbol in the cloud.
-- This runs inside Postgres after every inserted snapshot, so retention does not
-- depend on the browser being open and cannot accidentally prune another user.
create or replace function public.prune_snapshot_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.snapshots
  where id in (
    select id
    from public.snapshots
    where user_id = new.user_id
      and symbol = new.symbol
    order by captured_at desc, id desc
    offset 180
  );
  return new;
end;
$$;

revoke all on function public.prune_snapshot_history() from public;
revoke all on function public.prune_snapshot_history() from anon;
revoke all on function public.prune_snapshot_history() from authenticated;

drop trigger if exists snapshots_prune_after_insert on public.snapshots;
create trigger snapshots_prune_after_insert
after insert on public.snapshots
for each row execute function public.prune_snapshot_history();
