-- Crypto Asymmetry Engine v5.3 persistence schema
create table if not exists plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  symbol text not null,
  buy_price numeric,
  take_profit numeric,
  stop_loss numeric,
  max_fdv_tvl numeric,
  fee_drop numeric,
  amount numeric,
  entry_price numeric,
  entry_fees_30d numeric,
  notes text,
  updated_at timestamptz default now(),
  unique(user_id,symbol)
);
create table if not exists snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  symbol text not null,
  captured_at timestamptz default now(),
  price numeric, market_cap numeric, fdv numeric, tvl numeric,
  fees_30d numeric, revenue_30d numeric, circulating numeric,
  total_supply numeric, max_supply numeric
);
create index if not exists snapshots_user_symbol_time on snapshots(user_id,symbol,captured_at desc);
-- Enable RLS before production and add policies tied to auth.uid().
