-- Crypto Asymmetry Engine v8.9.6
-- Forward Signal Outcome Engine. Safe to re-run.

create table if not exists public.signal_outcomes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  signal_observation_id bigint not null references public.signal_observations(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  horizon_days integer not null check (horizon_days in (7,30,90)),
  matured_at date not null,
  entry_price numeric,
  exit_price numeric,
  asset_return_pct numeric,
  btc_return_pct numeric,
  btc_relative_return_pct numeric,
  max_favorable_excursion_pct numeric,
  max_adverse_excursion_pct numeric,
  max_drawdown_pct numeric,
  sample_days integer,
  outcome_version text not null default 'outcome-v1',
  calculated_at timestamptz not null default now(),
  unique(signal_observation_id,horizon_days)
);

create index if not exists signal_outcomes_user_asset_horizon
  on public.signal_outcomes(user_id,research_asset_id,horizon_days,matured_at desc);
create index if not exists signal_outcomes_observation
  on public.signal_outcomes(signal_observation_id,horizon_days);

alter table public.signal_outcomes enable row level security;
drop policy if exists "signal_outcomes_select_own" on public.signal_outcomes;
create policy "signal_outcomes_select_own" on public.signal_outcomes
  for select using (auth.uid()=user_id);

revoke all on public.signal_outcomes from anon, authenticated;
grant select on public.signal_outcomes to authenticated;
