-- v9.3 additive calibration + multi-year provenance
create table if not exists public.historical_price_daily (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint not null references public.research_assets(id) on delete cascade,price_date date not null,
 price numeric not null check(price>0),source text not null,source_symbol text,created_at timestamptz not null default now(),
 unique(user_id,research_asset_id,price_date,source));
create index if not exists historical_price_daily_asset_date_idx on public.historical_price_daily(user_id,research_asset_id,price_date);
create table if not exists public.calibration_results (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint references public.research_assets(id) on delete cascade,scope text not null check(scope in('asset','cross_asset')),
 cohort_key text not null,cohort_label text not null,horizon_days integer not null check(horizon_days in(7,30,90)),
 sample_count integer not null,asset_count integer not null default 1,median_return_pct numeric,median_btc_relative_pct numeric,
 median_mfe_pct numeric,median_mae_pct numeric,median_max_drawdown_pct numeric,positive_rate_pct numeric,
 btc_outperformance_rate_pct numeric,q25_return_pct numeric,q75_return_pct numeric,
 confidence_state text not null check(confidence_state in('INSUFFICIENT','LOW','MODERATE','STRONGER')),
 calibration_version text not null default 'calibration-v9.3',calculated_at timestamptz not null default now(),
 unique(user_id,research_asset_id,scope,cohort_key,horizon_days,calibration_version));
create index if not exists calibration_results_user_asset_idx on public.calibration_results(user_id,research_asset_id,horizon_days);
alter table public.historical_price_daily enable row level security;alter table public.calibration_results enable row level security;
drop policy if exists "historical prices own select" on public.historical_price_daily;
create policy "historical prices own select" on public.historical_price_daily for select to authenticated using(auth.uid()=user_id);
drop policy if exists "calibration own select" on public.calibration_results;
create policy "calibration own select" on public.calibration_results for select to authenticated using(auth.uid()=user_id);
revoke all on public.historical_price_daily from anon;revoke all on public.calibration_results from anon;
grant select on public.historical_price_daily to authenticated;grant select on public.calibration_results to authenticated;
