import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const V="calibration-v9.3",N=(v:any)=>v==null?null:Number(v);
function key(){const k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(k)return k;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||null}catch{return null}}
async function all(q:()=>any){let a:any[]=[];for(let f=0;;f+=1000){const{data,error}=await q().range(f,f+999);if(error)throw error;a.push(...(data||[]));if(!data||data.length<1000)break}return a}
function med(a:number[]){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function qt(a:number[],p:number){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;let i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l==h?a[l]:a[l]+(a[h]-a[l])*(i-l)}
const C:any[]=[
["trend_above_50_200","Above 50D + 200D",(x:any)=>x.trend_state==="ABOVE_50_200"],
["rsi_45_65","RSI 45–65",(x:any)=>N(x.rsi_14)!=null&&N(x.rsi_14)!>=45&&N(x.rsi_14)!<=65],
["btc_relative_positive","BTC-relative 30D > 0",(x:any)=>N(x.btc_relative_30d)!=null&&N(x.btc_relative_30d)!>0],
["pullback_30d","30D pullback",(x:any)=>N(x.return_30d)!=null&&N(x.return_30d)!<0],
["trend_plus_rsi","Above 50D + 200D & RSI 45–65",(x:any)=>x.trend_state==="ABOVE_50_200"&&N(x.rsi_14)!=null&&N(x.rsi_14)!>=45&&N(x.rsi_14)!<=65],
["trend_plus_relative","Above 50D + 200D & BTC-relative > 0",(x:any)=>x.trend_state==="ABOVE_50_200"&&N(x.btc_relative_30d)!=null&&N(x.btc_relative_30d)!>0],
["pullback_above_200","30D pullback while above 200D",(x:any)=>N(x.return_30d)!=null&&N(x.return_30d)!<0&&(x.trend_state==="ABOVE_50_200"||x.trend_state==="ABOVE_200_ONLY")]];
// Type guard so filtered arrays are number[] (plain .filter(Number.isFinite) leaves (number|null)[] and fails deno check).
const fin=(v:any):v is number=>Number.isFinite(v);
function sum(z:any[],scope:string){let ar=z.map(x=>N(x.asset_return_pct)).filter(fin),br=z.map(x=>N(x.btc_relative_return_pct)).filter(fin),mfe=z.map(x=>N(x.max_favorable_excursion_pct)).filter(fin),mae=z.map(x=>N(x.max_adverse_excursion_pct)).filter(fin),dd=z.map(x=>N(x.max_drawdown_pct)).filter(fin),ac=new Set(z.map(x=>x.research_asset_id)).size,s=z.length,conf=s<20?"INSUFFICIENT":scope==="cross_asset"&&ac<4?"LOW":s<40?"LOW":s<100?"MODERATE":"STRONGER";return{sample_count:s,asset_count:ac,median_return_pct:med(ar),median_btc_relative_pct:med(br),median_mfe_pct:med(mfe),median_mae_pct:med(mae),median_max_drawdown_pct:med(dd),positive_rate_pct:ar.length?100*ar.filter((x:number)=>x>0).length/ar.length:null,btc_outperformance_rate_pct:br.length?100*br.filter((x:number)=>x>0).length/br.length:null,q25_return_pct:qt(ar,.25),q75_return_pct:qt(ar,.75),confidence_state:conf}}
Deno.serve(async req=>{try{let s=Deno.env.get("MONITOR_CRON_SECRET")||"";if(!s||req.headers.get("x-monitor-secret")!==s)return new Response('{"error":"unauthorized"}',{status:401});let url=Deno.env.get("SUPABASE_URL"),sk=key();if(!url||!sk)throw Error("Supabase credentials unavailable");let db=createClient(url,sk,{auth:{persistSession:false}}),/* v9.3.1: an asset can have both replay-v9.2 and multi-year replay rows for the same dates. Use only its newest version
    (multi-year if present) so samples are not double counted. */
o=await all(()=>db.from("historical_replay_observations").select("id,user_id,research_asset_id,trend_state,rsi_14,btc_relative_30d,return_30d,replay_version").order("id")),u=await all(()=>db.from("historical_replay_outcomes").select("*").order("id")),multiAssets=new Set(o.filter((x:any)=>x.replay_version==="replay-v9.3.1-multiyear").map((x:any)=>`${x.user_id}:${x.research_asset_id}`)),map=new Map(o.filter((x:any)=>(x.replay_version==="replay-v9.3.1-multiyear")===multiAssets.has(`${x.user_id}:${x.research_asset_id}`)).map((x:any)=>[x.id,x])),j=u.filter((x:any)=>map.has(x.replay_observation_id)).map((x:any)=>({...x,...map.get(x.replay_observation_id)})),written=0;for(const uid of [...new Set(j.map((x:any)=>x.user_id))]){let x=j.filter((r:any)=>r.user_id===uid),ids=[...new Set(x.map((r:any)=>r.research_asset_id))],rows:any[]=[];for(const aid of ids)for(const h of[7,30,90])for(const[k,l,t]of C){let z=x.filter((r:any)=>r.research_asset_id===aid&&r.horizon_days===h&&t(r));rows.push({user_id:uid,research_asset_id:aid,scope:"asset",cohort_key:k,cohort_label:l,horizon_days:h,...sum(z,"asset"),calibration_version:V,calculated_at:new Date().toISOString()})}for(const h of[7,30,90])for(const[k,l,t]of C){let z=x.filter((r:any)=>r.horizon_days===h&&t(r));rows.push({user_id:uid,research_asset_id:null,scope:"cross_asset",cohort_key:k,cohort_label:l,horizon_days:h,...sum(z,"cross_asset"),calibration_version:V,calculated_at:new Date().toISOString()})}let{error}=await db.from("calibration_results").upsert(rows,{onConflict:"user_id,research_asset_id,scope,cohort_key,horizon_days,calibration_version"});if(error)throw error;written+=rows.length}return new Response(JSON.stringify({ok:true,version:V,observations:o.length,outcomes:u.length,calibration_rows:written,note:"Descriptive only; production scores unchanged."}),{headers:{"content-type":"application/json"}})}catch(e){return new Response(JSON.stringify({ok:false,error:String(e)}),{status:500,headers:{"content-type":"application/json"}})}})
