import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const H=[7,30,90],DAY=86400000;function key(){const x=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(x)return x;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||null}catch{return null}}
async function all(q:any){const o:any[]=[];for(let f=0;;f+=1000){const{data,error}=await q().range(f,f+999);if(error)throw error;o.push(...(data||[]));if(!data||data.length<1000)break}return o}
const date=(x:any)=>new Date(x).toISOString().slice(0,10);function near(r:any[],d:string){let b=null,g=Infinity,t=Date.parse(d+"T00:00:00Z");for(const x of r){let z=Math.abs(Date.parse(x.price_date+"T00:00:00Z")-t);if(z<g){g=z;b=x}}return b&&g<=3*DAY?b:null}
function calc(r:any[],btc:any[],s:string,h:number){const e=date(new Date(Date.parse(s+"T00:00:00Z")+h*DAY)),a0=near(r,s),a1=near(r,e),b0=near(btc,s),b1=near(btc,e);if(!a0||!a1||!b0||!b1)return null;const ep=+a0.price,xp=+a1.price,st=Date.parse(a0.price_date),en=Date.parse(a1.price_date),w=r.filter(x=>Date.parse(x.price_date)>=st&&Date.parse(x.price_date)<=en&&+x.price>0);if(w.length<Math.max(3,Math.floor(h*.55)))return null;let hi=ep,mfe=-Infinity,mae=Infinity,dd=0;for(const x of w){let p=+x.price;mfe=Math.max(mfe,(p/ep-1)*100);mae=Math.min(mae,(p/ep-1)*100);hi=Math.max(hi,p);dd=Math.min(dd,(p/hi-1)*100)}let ar=(xp/ep-1)*100,br=(+b1.price/+b0.price-1)*100;return{matured_at:e,entry_price:ep,exit_price:xp,asset_return_pct:ar,btc_return_pct:br,btc_relative_return_pct:ar-br,max_favorable_excursion_pct:mfe,max_adverse_excursion_pct:mae,max_drawdown_pct:dd,sample_days:w.length}}
// historical_price_daily.research_asset_id is NOT NULL, so BTC rows can only exist if BTC is itself a researched asset.
// Use persisted BTC-USD Coinbase history when present; otherwise fetch Coinbase BTC-USD daily candles directly
// (contiguous 250-day windows, at most 251 buckets), covering the earliest pending assessment.
async function btcBenchmark(db:any,sinceMs:number){
 const saved=await all(()=>db.from("historical_price_daily").select("price_date,price").eq("source","coinbase_exchange").eq("source_symbol","BTC-USD").order("price_date"));
 const byDate=new Map<string,any>();for(const x of saved)byDate.set(x.price_date,x);
 const earliest=saved.length?Date.parse(saved[0].price_date+"T00:00:00Z"):Infinity;
 if(saved.length&&earliest<=sinceMs-3*DAY)return[...byDate.values()];
 const begin=sinceMs-5*DAY,end=Date.now();
 for(let st=begin;st<=end;st+=250*DAY){const u=new URL("https://api.exchange.coinbase.com/products/BTC-USD/candles");u.searchParams.set("granularity","86400");u.searchParams.set("start",new Date(st).toISOString());u.searchParams.set("end",new Date(Math.min(end,st+250*DAY)).toISOString());
  const r=await fetch(u,{headers:{accept:"application/json","user-agent":"crypto-asymmetry-engine"}});if(!r.ok)throw Error(`Coinbase BTC-USD candles ${r.status}`);
  for(const c of await r.json()){const t=Number(c?.[0])*1000,px=Number(c?.[4]);if(Number.isFinite(t)&&px>0)byDate.set(date(t),{price_date:date(t),price:px})}
  await new Promise(z=>setTimeout(z,120))}
 return[...byDate.values()].sort((a:any,b:any)=>a.price_date<b.price_date?-1:1)}
Deno.serve(async req=>{try{const s=Deno.env.get("MONITOR_CRON_SECRET")||"";if(!s||req.headers.get("x-monitor-secret")!==s)return new Response('{"error":"unauthorized"}',{status:401});const url=Deno.env.get("SUPABASE_URL"),sk=key();if(!url||!sk)throw Error("Supabase credentials unavailable");const db=createClient(url,sk,{auth:{persistSession:false}}),a=await all(()=>db.from("ai_research_assessments").select("id,user_id,research_asset_id,observed_at").order("id")),ex=await all(()=>db.from("ai_assessment_outcomes").select("ai_assessment_id,horizon_days").order("id")),done=new Set(ex.map((x:any)=>`${x.ai_assessment_id}:${x.horizon_days}`)),today=Date.now(),p=a.flatMap((x:any)=>H.filter(h=>(today-Date.parse(x.observed_at))/DAY>=h&&!done.has(`${x.id}:${h}`)).map(h=>({x,h})));if(!p.length)return Response.json({ok:true,pending:0,inserted:0});const ids=[...new Set(p.map((q:any)=>q.x.research_asset_id))],prices=await all(()=>db.from("historical_price_daily").select("research_asset_id,price_date,price").in("research_asset_id",ids).eq("source","coinbase_exchange").order("price_date")),btc=await btcBenchmark(db,Math.min(...p.map((q:any)=>Date.parse(q.x.observed_at))));if(!btc.length)throw Error("BTC historical benchmark rows unavailable");const m=new Map();for(const x of prices){if(!m.has(x.research_asset_id))m.set(x.research_asset_id,[]);m.get(x.research_asset_id).push(x)}const rows=[];for(const q of p){const z=calc(m.get(q.x.research_asset_id)||[],btc,date(q.x.observed_at),q.h);if(z)rows.push({user_id:q.x.user_id,ai_assessment_id:q.x.id,research_asset_id:q.x.research_asset_id,horizon_days:q.h,...z,outcome_version:"ai-outcome-v9.5",calculated_at:new Date().toISOString()})}for(let i=0;i<rows.length;i+=500){const{error}=await db.from("ai_assessment_outcomes").upsert(rows.slice(i,i+500),{onConflict:"ai_assessment_id,horizon_days"});if(error)throw error}return Response.json({ok:true,pending:p.length,inserted:rows.length})}catch(e){return Response.json({ok:false,error:String(e)},{status:500})}})
