-- v10 Catalyst & Unlock Intelligence
create table if not exists public.catalyst_events (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint not null references public.research_assets(id) on delete cascade,
 event_key text not null,
 event_type text not null check(event_type in ('CATALYST','UNLOCK','EMISSION','GOVERNANCE','SECURITY','REGULATORY','TOKENOMICS','OTHER')),
 title text not null,
 event_date date,
 date_precision text not null default 'UNKNOWN' check(date_precision in ('DAY','MONTH','QUARTER','WINDOW','UNKNOWN')),
 status text not null check(status in ('UPCOMING','ONGOING','COMPLETED','DELAYED','CANCELLED','UNCONFIRMED')),
 impact_direction text not null default 'UNCLEAR' check(impact_direction in ('POSITIVE','NEGATIVE','MIXED','UNCLEAR')),
 importance text not null default 'MEDIUM' check(importance in ('LOW','MEDIUM','HIGH')),
 amount_tokens numeric, amount_usd numeric, pct_circulating numeric, pct_total_supply numeric,
 source_quality text not null check(source_quality in ('PRIMARY','STRONG_SECONDARY','SECONDARY','WEAK')),
 confidence text not null check(confidence in ('HIGH','MODERATE','LOW')),
 summary text not null, sources jsonb not null default '[]'::jsonb,
 first_seen_at timestamptz not null default now(), last_verified_at timestamptz not null default now(),
 model_version text not null default 'event-intel-v10',
 unique(user_id,research_asset_id,event_key)
);
create index if not exists catalyst_events_user_asset_date on public.catalyst_events(user_id,research_asset_id,event_date);
alter table public.catalyst_events enable row level security;
drop policy if exists "catalyst_events_select_own" on public.catalyst_events;
create policy "catalyst_events_select_own" on public.catalyst_events for select using(auth.uid()=user_id);
revoke all on public.catalyst_events from anon,authenticated; grant select on public.catalyst_events to authenticated;

create table if not exists public.catalyst_event_runs (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint not null references public.research_assets(id) on delete cascade,
 observed_at timestamptz not null default now(),
 catalyst_state text not null, unlock_state text not null, coverage_state text not null,
 summary text not null, event_count integer not null default 0,
 model text not null, model_version text not null default 'event-intel-v10',
 response_id text
);
create index if not exists catalyst_event_runs_user_asset_time on public.catalyst_event_runs(user_id,research_asset_id,observed_at desc);
alter table public.catalyst_event_runs enable row level security;
drop policy if exists "catalyst_event_runs_select_own" on public.catalyst_event_runs;
create policy "catalyst_event_runs_select_own" on public.catalyst_event_runs for select using(auth.uid()=user_id);
revoke all on public.catalyst_event_runs from anon,authenticated; grant select on public.catalyst_event_runs to authenticated;
