create table if not exists public.price_expectation_validation (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint references public.research_assets(id) on delete cascade,
 scope text not null check(scope in ('asset','cross_asset')),
 horizon_days integer not null check(horizon_days in(7,30,90)),
 sample_count integer not null default 0, independent_count integer not null default 0, asset_count integer not null default 0,
 range_coverage_pct numeric, central_mae_pct numeric, central_bias_pct numeric, directional_agreement_pct numeric,
 btc_relative_mae_pct numeric, zero_baseline_mae_pct numeric, unconditional_baseline_mae_pct numeric,
 mae_improvement_vs_zero_pct numeric, mae_improvement_vs_unconditional_pct numeric,
 low_confidence jsonb not null default '{}'::jsonb, moderate_confidence jsonb not null default '{}'::jsonb,
 validation_state text not null check(validation_state in ('INSUFFICIENT','WEAK','PROMISING')),
 diagnostics jsonb not null default '{}'::jsonb, validation_version text not null default 'price-validation-v10.3',
 calculated_at timestamptz not null default now());
create unique index if not exists price_expectation_validation_nnd
 on public.price_expectation_validation(user_id,scope,research_asset_id,horizon_days,validation_version) nulls not distinct;
alter table public.price_expectation_validation enable row level security;
drop policy if exists "price_expectation_validation_select_own" on public.price_expectation_validation;
create policy "price_expectation_validation_select_own" on public.price_expectation_validation for select using(auth.uid()=user_id);
revoke all on public.price_expectation_validation from anon,authenticated;
grant select on public.price_expectation_validation to authenticated;
