create table if not exists public.price_expectations (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint not null references public.research_assets(id) on delete cascade,
 observed_date date not null default current_date, observed_at timestamptz not null default now(),
 current_price numeric not null check(current_price>0), current_features jsonb not null, horizons jsonb not null,
 engine_version text not null default 'price-expectation-v10.2',
 unique(user_id,research_asset_id,observed_date,engine_version));
create index if not exists price_expectations_user_asset_time on public.price_expectations(user_id,research_asset_id,observed_at desc);
alter table public.price_expectations enable row level security;
drop policy if exists "price_expectations_select_own" on public.price_expectations;
create policy "price_expectations_select_own" on public.price_expectations for select using(auth.uid()=user_id);
revoke all on public.price_expectations from anon,authenticated;
grant select on public.price_expectations to authenticated;
