-- Crypto Asymmetry Engine v8.9.4
-- Position transaction ledger + position context in Signal Journal

create table if not exists public.position_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  symbol text not null,
  coingecko_id text not null,
  side text not null default 'buy' check (side in ('buy')),
  token_amount numeric not null check (token_amount > 0),
  price_usd numeric not null check (price_usd > 0),
  executed_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists position_transactions_user_asset_time
  on public.position_transactions(user_id,research_asset_id,executed_at desc,id desc);

alter table public.position_transactions enable row level security;

drop policy if exists "position_transactions_select_own" on public.position_transactions;
drop policy if exists "position_transactions_insert_own" on public.position_transactions;
drop policy if exists "position_transactions_update_own" on public.position_transactions;
drop policy if exists "position_transactions_delete_own" on public.position_transactions;

create policy "position_transactions_select_own" on public.position_transactions
  for select using (auth.uid()=user_id);
create policy "position_transactions_insert_own" on public.position_transactions
  for insert with check (auth.uid()=user_id);
create policy "position_transactions_update_own" on public.position_transactions
  for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "position_transactions_delete_own" on public.position_transactions
  for delete using (auth.uid()=user_id);

revoke all on public.position_transactions from anon;
grant select,insert,update,delete on public.position_transactions to authenticated;

alter table public.signal_observations add column if not exists position_token_amount numeric;
alter table public.signal_observations add column if not exists position_average_cost numeric;
alter table public.signal_observations add column if not exists position_cost_basis numeric;
alter table public.signal_observations add column if not exists position_unrealized_pnl numeric;
alter table public.signal_observations add column if not exists position_unrealized_pnl_pct numeric;
