-- Crypto Asymmetry Engine v9.0
-- AI Research Engine v1. Additive and safe to re-run.

create table if not exists public.ai_research_assessments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  model text not null,
  model_version text not null default 'ai-research-v9.0',
  stance text not null check (stance in ('CONSTRUCTIVE','MIXED','CAUTIOUS','INSUFFICIENT_EVIDENCE')),
  confidence text not null check (confidence in ('LOW','MODERATE','HIGH')),
  quant_ai_agreement text not null check (quant_ai_agreement in ('AGREES','PARTIAL','DISAGREES','NOT_ENOUGH_DATA')),
  summary text not null,
  assessment jsonb not null,
  input_snapshot jsonb not null,
  response_id text
);

create index if not exists ai_research_assessments_user_asset_time
  on public.ai_research_assessments(user_id,research_asset_id,observed_at desc);

alter table public.ai_research_assessments enable row level security;

drop policy if exists "ai_research_assessments_select_own" on public.ai_research_assessments;
drop policy if exists "ai_research_assessments_insert_own" on public.ai_research_assessments;

create policy "ai_research_assessments_select_own"
  on public.ai_research_assessments for select
  using (auth.uid()=user_id);

create policy "ai_research_assessments_insert_own"
  on public.ai_research_assessments for insert
  with check (auth.uid()=user_id);

revoke all on public.ai_research_assessments from anon;
grant select,insert on public.ai_research_assessments to authenticated;
