-- Crypto Asymmetry Engine v9.1
-- Automated Qualitative Intelligence. Additive and safe to re-run.

create table if not exists public.qualitative_research (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  model text not null,
  model_version text not null default 'qualitative-v9.1',
  catalyst_state text not null,
  value_capture_state text not null,
  dilution_state text not null,
  risk_state text not null,
  summary text not null,
  intelligence jsonb not null,
  response_id text
);

create index if not exists qualitative_research_user_asset_time
  on public.qualitative_research(user_id,research_asset_id,observed_at desc);

alter table public.qualitative_research enable row level security;

drop policy if exists "qualitative_research_select_own" on public.qualitative_research;
drop policy if exists "qualitative_research_insert_own" on public.qualitative_research;

create policy "qualitative_research_select_own"
  on public.qualitative_research for select using (auth.uid()=user_id);
create policy "qualitative_research_insert_own"
  on public.qualitative_research for insert with check (auth.uid()=user_id);

revoke all on public.qualitative_research from anon;
grant select,insert on public.qualitative_research to authenticated;
