-- v9.2 Historical Replay Engine
-- Quantitative, point-in-time replay only. It intentionally does NOT backfill
-- thesis, qualitative intelligence, catalysts, regime, or AI judgments.

create table if not exists public.historical_replay_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_date date not null,
  price numeric,
  return_7d numeric,
  return_30d numeric,
  ma_50 numeric,
  ma_200 numeric,
  price_vs_ma50_pct numeric,
  price_vs_ma200_pct numeric,
  rsi_14 numeric,
  drawdown_90d_pct numeric,
  btc_return_30d numeric,
  btc_relative_30d numeric,
  trend_state text check (trend_state in ('ABOVE_50_200','ABOVE_50_ONLY','ABOVE_200_ONLY','BELOW_50_200','INSUFFICIENT')),
  replay_version text not null default 'replay-v9.2',
  created_at timestamptz not null default now(),
  unique (user_id, research_asset_id, observed_date, replay_version)
);

create table if not exists public.historical_replay_outcomes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  replay_observation_id bigint not null references public.historical_replay_observations(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  horizon_days integer not null check (horizon_days in (7,30,90)),
  matured_at date not null,
  entry_price numeric not null,
  exit_price numeric not null,
  asset_return_pct numeric,
  btc_return_pct numeric,
  btc_relative_return_pct numeric,
  max_favorable_excursion_pct numeric,
  max_adverse_excursion_pct numeric,
  max_drawdown_pct numeric,
  sample_days integer,
  replay_version text not null default 'replay-v9.2',
  calculated_at timestamptz not null default now(),
  unique (replay_observation_id, horizon_days)
);

create index if not exists historical_replay_obs_user_asset_date_idx
  on public.historical_replay_observations(user_id,research_asset_id,observed_date desc);
create index if not exists historical_replay_outcomes_user_asset_horizon_idx
  on public.historical_replay_outcomes(user_id,research_asset_id,horizon_days);

alter table public.historical_replay_observations enable row level security;
alter table public.historical_replay_outcomes enable row level security;

drop policy if exists "replay observations own select" on public.historical_replay_observations;
create policy "replay observations own select" on public.historical_replay_observations
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "replay outcomes own select" on public.historical_replay_outcomes;
create policy "replay outcomes own select" on public.historical_replay_outcomes
  for select to authenticated using (auth.uid() = user_id);

revoke all on public.historical_replay_observations from anon;
revoke all on public.historical_replay_outcomes from anon;
grant select on public.historical_replay_observations to authenticated;
grant select on public.historical_replay_outcomes to authenticated;
