create table if not exists public.ai_assessment_outcomes (
id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
ai_assessment_id bigint not null references public.ai_research_assessments(id) on delete cascade,
research_asset_id bigint not null references public.research_assets(id) on delete cascade,
horizon_days integer not null check (horizon_days in (7,30,90)),matured_at date not null,entry_price numeric,exit_price numeric,
asset_return_pct numeric,btc_return_pct numeric,btc_relative_return_pct numeric,max_favorable_excursion_pct numeric,
max_adverse_excursion_pct numeric,max_drawdown_pct numeric,sample_days integer,outcome_version text not null default 'ai-outcome-v9.5',
calculated_at timestamptz not null default now(),unique(ai_assessment_id,horizon_days));
create index if not exists ai_assessment_outcomes_user_asset_horizon on public.ai_assessment_outcomes(user_id,research_asset_id,horizon_days,matured_at desc);
alter table public.ai_assessment_outcomes enable row level security;
drop policy if exists "ai_assessment_outcomes_select_own" on public.ai_assessment_outcomes;
create policy "ai_assessment_outcomes_select_own" on public.ai_assessment_outcomes for select using (auth.uid()=user_id);
revoke all on public.ai_assessment_outcomes from anon,authenticated; grant select on public.ai_assessment_outcomes to authenticated;
