-- v9.6 Decision & Expectation Engine
create table if not exists public.decision_expectations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  research_asset_id bigint not null references public.research_assets(id) on delete cascade,
  observed_at timestamptz not null default now(),
  observed_date date not null default current_date,
  mode text not null check (mode in ('entry','position')),
  posture text not null,
  confidence text not null check (confidence in ('LOW','MODERATE','HIGH')),
  summary text not null,
  expectation jsonb not null,
  input_snapshot jsonb not null,
  engine_version text not null default 'decision-v9.6',
  unique(user_id,research_asset_id,observed_date,mode)
);
create index if not exists decision_expectations_user_asset_time
  on public.decision_expectations(user_id,research_asset_id,observed_at desc);
alter table public.decision_expectations enable row level security;
drop policy if exists "decision_expectations_select_own" on public.decision_expectations;
create policy "decision_expectations_select_own" on public.decision_expectations
  for select using (auth.uid()=user_id);
revoke all on public.decision_expectations from anon,authenticated;
grant select on public.decision_expectations to authenticated;
