create table if not exists public.similarity_expectations (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 research_asset_id bigint not null references public.research_assets(id) on delete cascade,
 observed_date date not null default current_date, observed_at timestamptz not null default now(),
 current_features jsonb not null, horizons jsonb not null, validation jsonb,
 engine_version text not null default 'similarity-v9.7',
 unique(user_id,research_asset_id,observed_date,engine_version));
create index if not exists similarity_expectations_user_asset_time on public.similarity_expectations(user_id,research_asset_id,observed_at desc);
alter table public.similarity_expectations enable row level security;
drop policy if exists "similarity_expectations_select_own" on public.similarity_expectations;
create policy "similarity_expectations_select_own" on public.similarity_expectations for select using (auth.uid()=user_id);
revoke all on public.similarity_expectations from anon,authenticated;
grant select on public.similarity_expectations to authenticated;
