create table if not exists public.decision_outcomes (
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
 decision_expectation_id bigint not null references public.decision_expectations(id) on delete cascade,research_asset_id bigint not null references public.research_assets(id) on delete cascade,
 mode text not null,posture text not null,horizon_days integer not null check(horizon_days in(7,30,90)),matured_at date not null,entry_price numeric not null,exit_price numeric not null,
 asset_return_pct numeric,btc_return_pct numeric,btc_relative_return_pct numeric,max_favorable_excursion_pct numeric,max_adverse_excursion_pct numeric,max_drawdown_pct numeric,sample_days integer,
 outcome_version text not null default 'decision-outcome-v9.8',calculated_at timestamptz not null default now(),unique(decision_expectation_id,horizon_days));
alter table public.decision_outcomes enable row level security;
drop policy if exists "decision_outcomes_select_own" on public.decision_outcomes;
create policy "decision_outcomes_select_own" on public.decision_outcomes for select using(auth.uid()=user_id);
revoke all on public.decision_outcomes from anon,authenticated;grant select on public.decision_outcomes to authenticated;

create table if not exists public.decision_scorecard_results(
 id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,scope text not null check(scope in('asset','cross_asset')),
 research_asset_id bigint references public.research_assets(id) on delete cascade,mode text not null,posture text not null,horizon_days integer not null check(horizon_days in(7,30,90)),
 sample_count integer not null,asset_count integer not null,median_return_pct numeric,q25_return_pct numeric,q75_return_pct numeric,median_btc_relative_pct numeric,median_mfe_pct numeric,median_mae_pct numeric,
 median_max_drawdown_pct numeric,positive_rate_pct numeric,btc_outperformance_rate_pct numeric,confidence_state text not null,scorecard_version text not null default 'scorecard-v9.8',calculated_at timestamptz not null default now());
create unique index if not exists decision_scorecard_unique on public.decision_scorecard_results(user_id,scope,coalesce(research_asset_id,0),mode,posture,horizon_days,scorecard_version);
alter table public.decision_scorecard_results enable row level security;
drop policy if exists "decision_scorecard_select_own" on public.decision_scorecard_results;
create policy "decision_scorecard_select_own" on public.decision_scorecard_results for select using(auth.uid()=user_id);
revoke all on public.decision_scorecard_results from anon,authenticated;grant select on public.decision_scorecard_results to authenticated;
