-- v9.9 Calibration Lab
-- Proposals are advisory records only. Nothing here mutates decision thresholds.
create table if not exists public.calibration_proposals (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 scope text not null check (scope in ('entry','position')),
 metric_key text not null,
 current_rule jsonb not null default '{}'::jsonb,
 evidence_state text not null check (evidence_state in ('WAITING_FOR_EVIDENCE','REVIEW_READY','NO_CLEAR_SIGNAL')),
 proposal_state text not null default 'OBSERVATIONAL' check (proposal_state in ('OBSERVATIONAL','REVIEW_ONLY')),
 proposal jsonb,
 diagnostics jsonb not null default '{}'::jsonb,
 rationale text,
 calibration_version text not null default 'calibration-lab-v9.9',
 observed_date date not null default current_date,
 calculated_at timestamptz not null default now()
);
create unique index if not exists calibration_proposals_daily_unique
 on public.calibration_proposals(user_id,scope,metric_key,observed_date,calibration_version);
alter table public.calibration_proposals enable row level security;
drop policy if exists "calibration_proposals_select_own" on public.calibration_proposals;
create policy "calibration_proposals_select_own" on public.calibration_proposals for select using(auth.uid()=user_id);
revoke all on public.calibration_proposals from anon,authenticated;
grant select on public.calibration_proposals to authenticated;
