import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Activity,Search,WalletCards,Bell,ChevronRight,ShieldAlert,TrendingUp,Eye,LayoutDashboard}from'lucide-react';import'./style.css';
const assets=[
 {s:'AAVE',name:'Aave',research:80,entry:80,state:'Reassess for entry',theme:'DeFi lending / stablecoins',why:'Large lending network, strong economic activity and limited dilution.',risk:'Security/oracle events, falling borrowing demand or weak token value capture.',cap:'$2.25B',fdv:'$2.34B',signal:'Strong protocol economics'},
 {s:'PENDLE',name:'Pendle',research:78,entry:79,state:'Reassess for entry',theme:'Yield / RWA / stablecoins',why:'Yield trading can become infrastructure for tokenized and stablecoin yield markets.',risk:'Yield demand fades or protocol economics fail to scale.',cap:'$438M',fdv:'$710M',signal:'TVL and value capture worth watching'},
 {s:'AERO',name:'Aerodrome',research:73,entry:73,state:'Reassess for entry',theme:'Base liquidity / DeFi',why:'Measurable fees and holder revenue provide direct evidence beyond narrative.',risk:'Emissions or incentives overwhelm durable value capture.',cap:'$642M',fdv:'$1.28B',signal:'Strong fees; dilution needs scrutiny'},
 {s:'AKT',name:'Akash Network',research:73,entry:73,state:'Wait for confirmation',theme:'AI / DePIN / compute',why:'Small valuation creates potential asymmetry if decentralized compute demand accelerates.',risk:'AI narrative runs without measurable network demand.',cap:'$201M',fdv:'$262M',signal:'Needs utilization confirmation'},
 {s:'LINK',name:'Chainlink',research:72,entry:72,state:'Watch for entry',theme:'RWA infrastructure / interoperability',why:'Infrastructure exposure to tokenized finance with emerging revenue-funded value capture.',risk:'Adoption grows without enough LINK economic capture.',cap:'~$10B',fdv:'~$14B',signal:'Watch revenue and buybacks'},
 {s:'TAO',name:'Bittensor',research:67,entry:67,state:'Watch',theme:'Decentralized AI',why:'Strong decentralized AI exposure with deep liquidity.',risk:'Emissions and speculative attention outrun real subnet economics.',cap:'~$3.4B',fdv:'~$6.3B',signal:'Usage economics need validation'},
 {s:'ONDO',name:'Ondo',research:62,entry:62,state:'Wait',theme:'RWA / tokenized securities',why:'Strong institutional tokenization narrative and growing RWA footprint.',risk:'RWA growth may not accrue sufficient economic value to ONDO.',cap:'~$2.7B',fdv:'~$5.5B',signal:'Value capture unresolved'},
 {s:'TIA',name:'Celestia',research:58,entry:58,state:'Wait',theme:'Data availability',why:'Compressed valuation with improving supply profile.',risk:'Data-availability demand may not scale enough to support rerating.',cap:'~$473M',fdv:'—',signal:'Needs DA demand inflection'},
 {s:'SUI',name:'Sui',research:58,entry:58,state:'Do not chase',theme:'L1 / programmable finance',why:'High-liquidity ecosystem with meaningful growth potential.',risk:'Large remaining supply plus recent repricing can compress asymmetry.',cap:'~$4.6B',fdv:'~$11.2B',signal:'Timing and dilution unfavorable'},
];
const nav=[['Dashboard',LayoutDashboard],['Scanner',Search],['Portfolio',WalletCards],['Alerts',Bell]];
function Meter({n}){return <div className="meter"><i style={{width:n+'%'}}></i><b>{n}</b></div>}
function App(){const[page,setPage]=useState('Dashboard');const[selected,setSelected]=useState(null);const[q,setQ]=useState('');const list=assets.filter(a=>(a.s+a.name+a.theme).toLowerCase().includes(q.toLowerCase()));
 if(selected)return <Asset a={selected} back={()=>setSelected(null)}/>;
 return <div className="shell"><aside><div className="brand"><div>Λ</div><span>ASYMMETRY<small>ENGINE</small></span></div>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/>{n}</button>)}<div className="asideFoot"><span className="dot"></span> Research engine online<small>Snapshot: Sep 25, 2026</small></div></aside><main><header><div><small>CRYPTO ASYMMETRY ENGINE</small><h1>{page}</h1></div><div className="regime"><span></span> MARKET REGIME <b>NEUTRAL</b></div></header>
 {page==='Dashboard'&&<Dashboard open={setSelected}/>} {page==='Scanner'&&<Scanner list={list} q={q} setQ={setQ} open={setSelected}/>} {page==='Portfolio'&&<Empty icon={WalletCards} title="No active positions yet" body='Tell ChatGPT “I bought 300 PENDLE at $2.40” and use this page as the position ledger once the data layer is connected.'/ >} {page==='Alerts'&&<Alerts/>}</main></div>}
function Dashboard({open}){let top=assets.slice(0,5);return <><section className="hero"><div><span className="eyebrow">RESEARCH RADAR</span><h2>Find the gap between<br/><em>price and possibility.</em></h2><p>Research quality and entry attractiveness are deliberately separated. Strong project ≠ good entry.</p></div><div className="heroStat"><small>UNIVERSE</small><b>9</b><span>Coinbase candidates</span></div></section><div className="sectionTitle"><div><h3>Entry research queue</h3><p>Assets that currently deserve deeper entry analysis, not automatic buys.</p></div><button>Last review · Sep 25</button></div><div className="cards">{top.map(a=><Card a={a} open={open} key={a.s}/>)}</div><div className="split"><div className="panel"><h3><Activity size={18}/> Recent signals</h3>{assets.slice(0,4).map(a=><div className="signal" key={a.s}><b>{a.s}</b><span>{a.signal}</span><ChevronRight size={16}/></div>)}</div><div className="panel"><h3><ShieldAlert size={18}/> Engine rules</h3><p>Valuation, value capture, timing and catalysts can veto a strong narrative.</p><p>Every thesis gets an explicit bear case and invalidation condition.</p><p>Live data must be refreshed before acting on a setup.</p></div></div></>}
function Card({a,open}){return <button className="card" onClick={()=>open(a)}><div className="coin"><div>{a.s[0]}</div><span><b>{a.s}</b><small>{a.name}</small></span><ChevronRight/></div><div className="theme">{a.theme}</div><label>RESEARCH <Meter n={a.research}/></label><label>ENTRY <Meter n={a.entry}/></label><div className="state">{a.state}</div></button>}
function Scanner({list,q,setQ,open}){return <><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset, ticker, or narrative…"/></div><div className="table"><div className="tr head"><span>Asset</span><span>Narrative</span><span>Research</span><span>Entry</span><span>Status</span></div>{list.map(a=><button className="tr" onClick={()=>open(a)} key={a.s}><span><b>{a.s}</b><small>{a.name}</small></span><span>{a.theme}</span><span>{a.research}</span><span>{a.entry}</span><span className="pill">{a.state}</span></button>)}</div></>}
function Alerts(){return <div className="panel alertPanel"><h3><Bell size={18}/> Monitoring blueprint</h3>{['Thesis metric materially improves → rerun Entry Score','Price falls while fundamentals hold → rerun valuation','Price surges without fundamentals → reassess asymmetry','Revenue / users / fees deteriorate → thesis review','Large unlock approaches → supply-risk review','Security or legal impairment → hard review'].map(x=><div className="signal"><span>{x}</span></div>)}</div>}
function Empty({icon:I,title,body}){return <div className="empty"><I size={40}/><h2>{title}</h2><p>{body}</p></div>}
function Asset({a,back}){return <div className="detail"><button className="back" onClick={back}>← Back to dashboard</button><div className="detailHead"><div><span className="eyebrow">{a.theme}</span><h1>{a.name} <small>{a.s}</small></h1><div className="state">{a.state}</div></div><div className="scorePair"><div><small>RESEARCH</small><b>{a.research}</b><span>/100</span></div><div><small>ENTRY</small><b>{a.entry}</b><span>/100</span></div></div></div><div className="detailGrid"><div className="panel wide"><h3>Why it is interesting</h3><p>{a.why}</p><h3>Strongest bear case</h3><p>{a.risk}</p></div><div className="panel metrics"><h3>Valuation snapshot</h3><div><span>Market cap</span><b>{a.cap}</b></div><div><span>FDV</span><b>{a.fdv}</b></div><div><span>Research status</span><b>{a.state}</b></div></div><div className="panel wide"><h3><TrendingUp size={18}/> Decision framework</h3><p>This snapshot is research context, not a live trade instruction. Before an entry decision, refresh price, supply, fundamentals, catalyst timing and downside scenarios.</p></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
