import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Search,WalletCards,Bell,LayoutDashboard,RefreshCw,Wifi,WifiOff,ArrowUpRight,Clock3,FlaskConical,Eye,ShieldAlert,Activity,Target,ChevronRight}from"lucide-react";import"./style.css";
const A=[
["AAVE","aave","Aave",80,"DeFi lending / stablecoins","watch","Large lending network with substantial on-chain credit activity and comparatively limited dilution.","Refresh revenue, borrowing growth and current token-capture mechanics.",["Borrowing and stablecoin activity expands","Protocol economics strengthen"],["Security/oracle event","Economics grow without enough token capture"]],
["PENDLE","pendle","Pendle",78,"Yield / RWA / stablecoins","strengthening","Yield-trading infrastructure can benefit from growth in stablecoins, RWAs and tokenized yield.","Refresh TVL, fees, revenue and sPENDLE economics before enabling Entry Score.",["TVL and fee growth outpace valuation","Holder value capture remains durable"],["Yield demand fades","Fee growth or token capture weakens"]],
["AERO","aerodrome-finance","Aerodrome",73,"Base liquidity / DeFi","watch","A major Base liquidity venue with measurable fees and holder economics.","Refresh emissions, organic volume, fees and holder revenue.",["Base activity accelerates","Organic volume grows faster than emissions"],["Emissions dominate economics","DEX competition erodes share"]],
["AKT","akash-network","Akash Network",73,"AI / DePIN / compute","research","A smaller-cap expression of decentralized compute if real network demand accelerates.","Measure compute utilization, spend, revenue and customer growth.",["Compute utilization rises","AI demand converts into paid usage"],["Narrative outruns utilization","Token demand fails to follow usage"]],
["LINK","chainlink","Chainlink",72,"RWA infrastructure / interoperability","watch","Infrastructure exposure to tokenized finance, oracles and interoperability with emerging value capture.","Refresh protocol revenue, buybacks and current valuation multiples.",["CCIP and RWA usage expands","Revenue-funded economics grow"],["Adoption grows without LINK capture","Valuation outruns economics"]],
["TAO","bittensor","Bittensor",67,"Decentralized AI","research","Liquid decentralized-AI exposure with potentially valuable subnet economics.","Validate real subnet demand, emissions burden and value capture.",["Paid subnet demand becomes measurable","Economics outrun emissions"],["Speculation dominates demand","Emissions dilute holders"]],
["ONDO","ondo-finance","Ondo",62,"RWA / tokenized securities","research","Institutional tokenization growth could create a large ecosystem, but token capture is unresolved.","Resolve current token rights and protocol-revenue attribution.",["Tokenized assets scale rapidly","Token economics become clearer"],["RWA growth bypasses holders","Economics accrue elsewhere"]],
["TIA","celestia","Celestia",58,"Data availability","research","A compressed data-availability infrastructure bet if paid DA demand inflects.","Refresh paid blob demand, fees, issuance and competitive share.",["Blob demand rises","Supply pressure declines"],["DA becomes commoditized","Demand stays weak"]],
["SUI","sui","Sui",58,"L1 / programmable finance","wait","A liquid high-growth L1 where adoption must outrun remaining dilution and valuation.","Refresh unlock schedule, ecosystem revenue and active economic usage.",["Economic activity compounds","Growth outruns unlock pressure"],["Unlocks compress returns","Price outruns fundamentals"]]
].map(x=>({s:x[0],id:x[1],name:x[2],research:x[3],theme:x[4],setup:x[5],thesis:x[6],missing:x[7],bull:x[8],bear:x[9]}));
const LLAMA={AAVE:"aave",PENDLE:"pendle",AERO:"aerodrome",ONDO:"ondo-finance"};
const fmtChange=n=>n==null?"—":`${n>=0?"+":""}${Number(n).toFixed(1)}%`;
const meta={strengthening:["Setup strengthening",ArrowUpRight],watch:["Watch / validate",Eye],research:["Research only",FlaskConical],wait:["Wait / reassess",Clock3]},money=n=>n==null?"—":n>=1e9?"$"+(n/1e9).toFixed(2)+"B":n>=1e6?"$"+(n/1e6).toFixed(1)+"M":n>=1e3?"$"+(n/1e3).toFixed(1)+"K":"$"+Number(n).toLocaleString(undefined,{maximumFractionDigits:n<1?4:2}),pct=n=>n==null?"—":`${n>=0?"+":""}${n.toFixed(2)}%`;
function Signal({t}){let[l,I]=meta[t]||meta.research;return <span className={"sig "+t}><I size={12}/>{l}</span>}
function useMarket(){let[d,sd]=useState({}),[status,ss]=useState("loading"),[updated,su]=useState(null);async function refresh(){ss("loading");try{let ids=A.map(a=>a.id).join(","),r=await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${ids}&sparkline=false&price_change_percentage=24h`);if(!r.ok)throw 0;let j=await r.json(),m={};j.forEach(x=>m[x.id]=x);sd(m);su(new Date());ss("live")}catch{ss("error")}}useEffect(()=>{refresh();let t=setInterval(refresh,120000);return()=>clearInterval(t)},[]);return{d,status,updated,refresh}}
function useFundamentals(){const[d,setD]=useState({}),[status,setStatus]=useState("loading"),[updated,setUpdated]=useState(null);
async function refresh(){setStatus("loading");try{
 const protocols=await fetch("https://api.llama.fi/protocols").then(r=>{if(!r.ok)throw 0;return r.json()});
 const bySlug={};protocols.forEach(p=>bySlug[p.slug]=p);
 const entries=await Promise.all(Object.entries(LLAMA).map(async([sym,slug])=>{
  const p=bySlug[slug]||{};
  const [fees,rev]=await Promise.all([
   fetch(`https://api.llama.fi/summary/fees/${slug}?dataType=dailyFees`).then(r=>r.ok?r.json():null).catch(()=>null),
   fetch(`https://api.llama.fi/summary/fees/${slug}?dataType=dailyRevenue`).then(r=>r.ok?r.json():null).catch(()=>null)
  ]);
  return [sym,{tvl:p.tvl??null,tvl1d:p.change_1d??null,tvl7d:p.change_7d??null,tvl1m:p.change_1m??null,fees30d:fees?.total30d??null,fees7d:fees?.total7d??null,revenue30d:rev?.total30d??null,revenue7d:rev?.total7d??null}];
 }));
 setD(Object.fromEntries(entries));setUpdated(new Date());setStatus("live");
}catch(e){setStatus("error")}}
useEffect(()=>{refresh();let t=setInterval(refresh,300000);return()=>clearInterval(t)},[]);
return{d,status,updated,refresh}}
function App(){let[page,sp]=useState("Dashboard"),[sel,setSel]=useState(),[q,sq]=useState(""),m=useMarket(),f=useFundamentals(),list=useMemo(()=>A.filter(a=>(a.s+a.name+a.theme).toLowerCase().includes(q.toLowerCase())),[q]);if(sel)return <Detail a={sel} m={m.d[sel.id]} back={()=>setSel()}/>;return <div className="shell"><aside><div className="brand">Λ <b>ASYMMETRY<small>ENGINE</small></b></div>{[["Dashboard",LayoutDashboard],["Scanner",Search],["Portfolio",WalletCards],["Alerts",Bell]].map(([n,I])=><button className={page===n?"active":""} onClick={()=>sp(n)}><I size={18}/>{n}</button>)}</aside><main><header><div><small>CRYPTO ASYMMETRY ENGINE · V4</small><h1>{page}</h1></div><button className={"live "+m.status} onClick={m.refresh}>{m.status==="live"?<Wifi size={14}/>:m.status==="error"?<WifiOff size={14}/>:<RefreshCw size={14}/>} {m.status.toUpperCase()} {m.updated&&m.updated.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</button></header>{page==="Dashboard"&&<Dash m={m} f={f} open={setSel}/>} {page==="Scanner"&&<Scan m={m} f={f} list={list} q={q} sq={sq} open={setSel}/>} {page==="Portfolio"&&<Empty/>}{page==="Alerts"&&<Alerts/>}</main></div>}
function Dash({m,f,open}){return <><section className="hero"><span>DECISION RADAR</span><h2>Research the thesis.<br/><em>Monitor the gap.</em></h2><p>Live market data plus evidence-gated research states. Setup labels are research prompts, not automatic trade instructions.</p></section><div className="title"><div><h3>Highest-priority research</h3><p>Open a candidate for thesis, evidence gaps and reassessment triggers.</p></div></div><div className="cards">{A.slice(0,5).map(a=><Card a={a} m={m.d[a.id]} f={f.d[a.s]} open={open}/>)}</div><div className="split"><section className="panel"><h3><Activity size={17}/> What changed?</h3>{A.slice(0,5).map(a=><button className="row" onClick={()=>open(a)}><b>{a.s}</b><span>{a.missing}</span><ChevronRight size={14}/></button>)}</section><section className="panel"><h3><Target size={17}/> Fundamentals feed</h3><p><b>DefiLlama:</b> {f.status==="live"?" LIVE":f.status==="loading"?" REFRESHING":" OFFLINE"}</p><p>TVL, TVL momentum, 30d fees and 30d protocol revenue are pulled independently where a protocol mapping exists.</p><p>Unsupported assets stay blank rather than receiving proxy values.</p></section><section className="panel"><h3><Target size={17}/> Decision workflow</h3><p><b>Research Score</b> prioritizes investigation.</p><p><b>Setup state</b> identifies what needs validation now.</p><p><b>Evidence gate</b> prevents unsupported Entry Scores.</p><p><b>Triggers</b> tell you when a thesis deserves reassessment.</p></section></div></>}
function Card({a,m,f,open}){return <button className="card" onClick={()=>open(a)}><div className="coin"><b>{a.s}</b><small>{a.name}</small></div><p>{a.theme}</p><div className="price"><b>{m?money(m.current_price):"—"}</b><span className={(m?.price_change_percentage_24h||0)>=0?"up":"down"}>{m?pct(m.price_change_percentage_24h):"—"}</span></div><div className="fundmini"><span>TVL {f?.tvl?money(f.tvl):"—"}</span><span>30d fees {f?.fees30d?money(f.fees30d):"—"}</span></div><label>RESEARCH <b>{a.research}/100</b></label><Signal t={a.setup}/></button>}
function Scan({m,f,list,q,sq,open}){return <><div className="search"><Search size={17}/><input value={q} onChange={e=>sq(e.target.value)} placeholder="Search asset, ticker or narrative…"/></div><div className="table">{list.map(a=>{let x=m.d[a.id];return <button onClick={()=>open(a)}><span><b>{a.s}</b><small>{a.name}</small></span><span>{x?money(x.current_price):"—"}<small className={(x?.price_change_percentage_24h||0)>=0?"up":"down"}>{x?pct(x.price_change_percentage_24h):"—"}</small></span><span>{x?money(x.market_cap):"—"}</span><span>{x?money(x.fully_diluted_valuation):"—"}</span><span>{a.research}</span><Signal t={a.setup}/></button>})}</div></>}
function Detail({a,m,back}){let fundamentals=useFundamentals(),f=fundamentals.d[a.s],ratio=m?.market_cap&&m?.fully_diluted_valuation?m.fully_diluted_valuation/m.market_cap:null;return <div className="detail"><button className="back" onClick={back}>← Back</button><div className="head"><div><small>{a.theme}</small><h1>{a.name} <i>{a.s}</i></h1><Signal t={a.setup}/></div><div className="score"><small>RESEARCH SNAPSHOT</small><b>{a.research}</b><span>/100</span></div></div><div className="grid"><section className="panel thesis"><h3><FlaskConical size={17}/> Core thesis</h3><p>{a.thesis}</p><div className="cols"><div><h4>Strengthens thesis</h4>{a.bull.map(x=><p className="up">↑ {x}</p>)}</div><div><h4>Weakens thesis</h4>{a.bear.map(x=><p className="down">↓ {x}</p>)}</div></div></section><section className="panel metrics"><h3>Live market</h3>{[["Price",m?money(m.current_price):"—"],["24h",m?pct(m.price_change_percentage_24h):"—"],["Market cap",m?money(m.market_cap):"—"],["FDV",m?money(m.fully_diluted_valuation):"—"],["FDV / MC",ratio?ratio.toFixed(2)+"×":"—"],["24h volume",m?money(m.total_volume):"—"]].map(x=><div><span>{x[0]}</span><b>{x[1]}</b></div>)}</section><section className="panel metrics"><h3>Live fundamentals</h3>{[["TVL",f?.tvl?money(f.tvl):"—"],["TVL 1d",fmtChange(f?.tvl1d)],["TVL 7d",fmtChange(f?.tvl7d)],["TVL 1m",fmtChange(f?.tvl1m)],["Fees 30d",f?.fees30d?money(f.fees30d):"—"],["Revenue 30d",f?.revenue30d?money(f.revenue30d):"—"]].map(x=><div><span>{x[0]}</span><b>{x[1]}</b></div>)}<p className="sourceNote">DefiLlama live feed · unsupported metrics remain blank</p></section><section className="panel"><h3><ShieldAlert size={17}/> Evidence gate</h3><p>{a.missing}</p><strong>ENTRY SCORE LOCKED</strong></section><section className="panel"><h3><Activity size={17}/> Reassessment</h3><p>Fundamentals improve while valuation compresses → rerun setup.</p><p>Price outruns fundamentals → reassess valuation.</p><p>Unlock, exploit, catalyst failure or economic deterioration → thesis review.</p></section></div></div>}
function Empty(){return <div className="empty"><WalletCards size={38}/><h2>Position persistence comes next</h2><p>Positions will store cost basis, thesis at entry, catalysts and reassessment conditions. The app will not invent holdings.</p></div>}
function Alerts(){return <section className="panel alerts"><h3><Bell size={17}/> Reassessment rules</h3>{["Fundamentals improve + valuation compresses → rerun setup","Price expands without matching fundamentals → valuation review","Revenue, users or fees deteriorate → thesis review","Large unlock or emissions change → dilution review","Catalyst succeeds or fails → update thesis and valuation","Security or major legal impairment → hard review"].map(x=><p>{x}</p>)}</section>}
createRoot(document.getElementById("root")).render(<App/>);