import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,Search,WalletCards,Bell,ChevronRight,ShieldAlert,TrendingUp,LayoutDashboard,RefreshCw,Wifi,WifiOff}from'lucide-react';
import'./style.css';

const assets=[
 {s:'AAVE',id:'aave',name:'Aave',research:80,state:'Deep research',theme:'DeFi lending / stablecoins',why:'Large lending network, strong economic activity and limited dilution.',risk:'Security/oracle events, falling borrowing demand or weak token value capture.',signal:'Strong protocol economics'},
 {s:'PENDLE',id:'pendle',name:'Pendle',research:78,state:'Deep research',theme:'Yield / RWA / stablecoins',why:'Yield trading can become infrastructure for tokenized and stablecoin yield markets.',risk:'Yield demand fades or protocol economics fail to scale.',signal:'TVL and value capture worth watching'},
 {s:'AERO',id:'aerodrome-finance',name:'Aerodrome',research:73,state:'Deep research',theme:'Base liquidity / DeFi',why:'Measurable fees and holder revenue provide direct evidence beyond narrative.',risk:'Emissions or incentives overwhelm durable value capture.',signal:'Strong fees; dilution needs scrutiny'},
 {s:'AKT',id:'akash-network',name:'Akash Network',research:73,state:'Deep research',theme:'AI / DePIN / compute',why:'Small valuation creates potential asymmetry if decentralized compute demand accelerates.',risk:'AI narrative runs without measurable network demand.',signal:'Needs utilization confirmation'},
 {s:'LINK',id:'chainlink',name:'Chainlink',research:72,state:'Deep research',theme:'RWA infrastructure / interoperability',why:'Infrastructure exposure to tokenized finance with emerging revenue-funded value capture.',risk:'Adoption grows without enough LINK economic capture.',signal:'Watch revenue and buybacks'},
 {s:'TAO',id:'bittensor',name:'Bittensor',research:67,state:'Watch / research',theme:'Decentralized AI',why:'Strong decentralized AI exposure with deep liquidity.',risk:'Emissions and speculative attention outrun real subnet economics.',signal:'Usage economics need validation'},
 {s:'ONDO',id:'ondo-finance',name:'Ondo',research:62,state:'Watch / research',theme:'RWA / tokenized securities',why:'Strong institutional tokenization narrative and growing RWA footprint.',risk:'RWA growth may not accrue sufficient economic value to ONDO.',signal:'Value capture unresolved'},
 {s:'TIA',id:'celestia',name:'Celestia',research:58,state:'Watch',theme:'Data availability',why:'Compressed valuation with improving supply profile.',risk:'Data-availability demand may not scale enough to support rerating.',signal:'Needs DA demand inflection'},
 {s:'SUI',id:'sui',name:'Sui',research:58,state:'Watch',theme:'L1 / programmable finance',why:'High-liquidity ecosystem with meaningful growth potential.',risk:'Large remaining supply plus repricing can compress asymmetry.',signal:'Timing and dilution need review'},
];
const nav=[['Dashboard',LayoutDashboard],['Scanner',Search],['Portfolio',WalletCards],['Alerts',Bell]];
const money=n=>n==null?'—':n>=1e9?'$'+(n/1e9).toFixed(2)+'B':n>=1e6?'$'+(n/1e6).toFixed(1)+'M':n>=1e3?'$'+(n/1e3).toFixed(1)+'K':'$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:n<1?4:2});
const pct=n=>n==null?'—':`${n>=0?'+':''}${n.toFixed(2)}%`;
function Meter({n}){return <div className="meter"><i style={{width:Math.min(100,n)+'%'}}></i><b>{n}</b></div>}
function useMarket(){const[data,setData]=useState({});const[status,setStatus]=useState('loading');const[updated,setUpdated]=useState(null);const[err,setErr]=useState('');
 const refresh=async()=>{setStatus('loading');setErr('');try{const ids=assets.map(a=>a.id).join(',');const url=`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${ids}&order=market_cap_desc&per_page=50&page=1&sparkline=false&price_change_percentage=24h,7d`;const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`Market API returned ${r.status}`);const j=await r.json();const map={};j.forEach(x=>map[x.id]=x);setData(map);setUpdated(new Date());setStatus('live');}catch(e){setStatus('error');setErr(e.message||'Live market data unavailable');}};
 useEffect(()=>{refresh();const t=setInterval(refresh,120000);return()=>clearInterval(t)},[]);return{data,status,updated,err,refresh};}
function App(){const[page,setPage]=useState('Dashboard');const[selected,setSelected]=useState(null);const[q,setQ]=useState('');const market=useMarket();const list=useMemo(()=>assets.filter(a=>(a.s+a.name+a.theme).toLowerCase().includes(q.toLowerCase())),[q]);
 if(selected)return <Asset a={selected} m={market.data[selected.id]} market={market} back={()=>setSelected(null)}/>;
 return <div className="shell"><aside><div className="brand"><div>Λ</div><span>ASYMMETRY<small>ENGINE</small></span></div>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/>{n}</button>)}<div className="asideFoot"><span className="dot"></span> Research engine online<small>Research snapshot · Sep 25, 2026</small></div></aside><main><header><div><small>CRYPTO ASYMMETRY ENGINE</small><h1>{page}</h1></div><LiveBadge market={market}/></header>
 {page==='Dashboard'&&<Dashboard open={setSelected} market={market}/>} {page==='Scanner'&&<Scanner list={list} q={q} setQ={setQ} open={setSelected} market={market}/>} {page==='Portfolio'&&<Empty icon={WalletCards} title="No active positions yet" body='Position persistence comes next. For now, portfolio data is intentionally not fabricated.'/ >} {page==='Alerts'&&<Alerts/>}</main></div>}
function LiveBadge({market}){return <button className={`liveBadge ${market.status}`} onClick={market.refresh} title={market.err||'Refresh market data'}>{market.status==='live'?<Wifi size={14}/>:market.status==='error'?<WifiOff size={14}/>:<RefreshCw className="spin" size={14}/>}<span>{market.status==='live'?'LIVE MARKET':market.status==='error'?'DATA OFFLINE':'REFRESHING'}</span><b>{market.updated?market.updated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</b></button>}
function Dashboard({open,market}){let top=assets.slice(0,5);return <><section className="hero"><div><span className="eyebrow">RESEARCH RADAR</span><h2>Find the gap between<br/><em>price and possibility.</em></h2><p>Live market data is separated from the research snapshot. Entry scores stay disabled until the scoring model is recalculated correctly.</p></div><div className="heroStat"><small>UNIVERSE</small><b>9</b><span>Coinbase research candidates</span></div></section><div className="sectionTitle"><div><h3>Research queue</h3><p>Live price/valuation + snapshot research context. Not automatic buys.</p></div><button onClick={market.refresh}><RefreshCw size={14}/> Refresh</button></div><div className="cards">{top.map(a=><Card a={a} m={market.data[a.id]} open={open} key={a.s}/>)}</div><div className="split"><div className="panel"><h3><Activity size={18}/> Recent research signals</h3>{assets.slice(0,4).map(a=><div className="signal" key={a.s}><b>{a.s}</b><span>{a.signal}</span><ChevronRight size={16}/></div>)}</div><div className="panel"><h3><ShieldAlert size={18}/> Data integrity</h3><p>Price, market cap, FDV and market moves are fetched live when the market feed is available.</p><p>Research scores are dated snapshots and do not automatically change with price.</p><p>Entry Score is intentionally withheld until its component bounds and live inputs are rebuilt.</p></div></div></>}
function Card({a,m,open}){return <button className="card" onClick={()=>open(a)}><div className="coin"><div>{a.s[0]}</div><span><b>{a.s}</b><small>{a.name}</small></span><ChevronRight/></div><div className="theme">{a.theme}</div><div className="marketLine"><b>{m?money(m.current_price):'—'}</b><span className={(m?.price_change_percentage_24h||0)>=0?'up':'down'}>{m?pct(m.price_change_percentage_24h):'—'}</span></div><label>RESEARCH SNAPSHOT <Meter n={a.research}/></label><label>ENTRY <div className="pending">Pending refresh</div></label><div className="state">{a.state}</div></button>}
function Scanner({list,q,setQ,open,market}){return <><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset, ticker, or narrative…"/></div><div className="table"><div className="tr head"><span>Asset</span><span>Price / 24h</span><span>Market cap</span><span>FDV</span><span>Research</span></div>{list.map(a=>{const m=market.data[a.id];return <button className="tr" onClick={()=>open(a)} key={a.s}><span><b>{a.s}</b><small>{a.name}</small></span><span><b>{m?money(m.current_price):'—'}</b><small className={(m?.price_change_percentage_24h||0)>=0?'up':'down'}>{m?pct(m.price_change_percentage_24h):'—'}</small></span><span>{m?money(m.market_cap):'—'}</span><span>{m?money(m.fully_diluted_valuation):'—'}</span><span>{a.research}</span></button>})}</div></>}
function Alerts(){return <div className="panel alertPanel"><h3><Bell size={18}/> Monitoring blueprint</h3>{['Thesis metric materially improves → rerun Entry Score','Price falls while fundamentals hold → rerun valuation','Price surges without fundamentals → reassess asymmetry','Revenue / users / fees deteriorate → thesis review','Large unlock approaches → supply-risk review','Security or legal impairment → hard review'].map((x,i)=><div className="signal" key={i}><span>{x}</span></div>)}</div>}
function Empty({icon:I,title,body}){return <div className="empty"><I size={40}/><h2>{title}</h2><p>{body}</p></div>}
function Asset({a,m,market,back}){return <div className="detail"><button className="back" onClick={back}>← Back to dashboard</button><div className="detailHead"><div><span className="eyebrow">{a.theme}</span><h1>{a.name} <small>{a.s}</small></h1><div className="state">{a.state}</div></div><div className="scorePair"><div><small>RESEARCH SNAPSHOT</small><b>{a.research}</b><span>/100*</span></div><div><small>ENTRY</small><b className="na">—</b><span>rebuild pending</span></div></div></div><div className="detailGrid"><div className="panel wide"><h3>Why it is interesting</h3><p>{a.why}</p><h3>Strongest bear case</h3><p>{a.risk}</p></div><div className="panel metrics"><h3>Live market snapshot</h3><div><span>Price</span><b>{m?money(m.current_price):'—'}</b></div><div><span>24h</span><b className={(m?.price_change_percentage_24h||0)>=0?'up':'down'}>{m?pct(m.price_change_percentage_24h):'—'}</b></div><div><span>Market cap</span><b>{m?money(m.market_cap):'—'}</b></div><div><span>FDV</span><b>{m?money(m.fully_diluted_valuation):'—'}</b></div><div><span>24h volume</span><b>{m?money(m.total_volume):'—'}</b></div><div><span>Feed</span><b>{market.status==='live'?'Live':'Unavailable'}</b></div></div><div className="panel wide"><h3><TrendingUp size={18}/> Decision framework</h3><p>Live market data alone is not an entry signal. The next layer will refresh protocol fundamentals, dilution, catalysts and the corrected Entry Score before an asset can become an Entry Candidate.</p><p className="footnote">* Research score is a dated research snapshot, not a live quantitative rating.</p></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
