const CG="https://api.coingecko.com/api/v3";
const num=v=>v==null||v===""?null:Number(v),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),ret=(a,b)=>a>0&&b>0?(b/a-1)*100:null,avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const headers=()=>{const h={accept:"application/json"},k=process.env.COINGECKO_DEMO_API_KEY;if(k)h["x-cg-demo-api-key"]=k;return h};
async function j(url,h={accept:"application/json"}){try{const r=await fetch(url,{headers:h});return r.ok?await r.json():null}catch{return null}}
function rsi(xs,n=14){if(xs.length<n+1)return null;let g=0,l=0;for(let i=xs.length-n;i<xs.length;i++){const d=xs[i]-xs[i-1];if(d>=0)g+=d;else l-=d}if(l===0)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
function stats(prices,btc){const p=prices.map(x=>x[1]).filter(Number.isFinite),b=btc.map(x=>x[1]).filter(Number.isFinite);if(p.length<31)return null;const last=p.at(-1),at=n=>p[Math.max(0,p.length-1-n)],ma=n=>p.length>=n?avg(p.slice(-n)):null,m20=ma(20),m50=ma(50),m200=ma(200),r7=ret(at(7),last),r30=ret(at(30),last),r90=ret(at(90),last),r180=ret(at(180),last),br30=b.length>=31?ret(b[b.length-31],b.at(-1)):null,br90=b.length>=91?ret(b[b.length-91],b.at(-1)):null,hi90=Math.max(...p.slice(-Math.min(90,p.length))),dd90=hi90>0?(last/hi90-1)*100:null,dist50=m50?ret(m50,last):null,dist200=m200?ret(m200,last):null,rv=rsi(p);let pattern="MIXED";if(m50&&m200&&last>m50&&m50>m200)pattern="UPTREND";else if(m200&&last<m200)pattern="BELOW 200D";else if(m50&&last>m50)pattern="ABOVE 50D";const extended=(r30!=null&&r30>35)||(dist50!=null&&dist50>22)||(rv!=null&&rv>72),constructive=!extended&&(pattern==="UPTREND"||pattern==="ABOVE 50D")&&(rv==null||rv<70),pullback=pattern==="UPTREND"&&dist50!=null&&dist50>=-8&&dist50<=8&&rv!=null&&rv>=38&&rv<=62;return{price:last,ma20:m20,ma50:m50,ma200:m200,rsi14:rv,return7d:r7,return30d:r30,return90d:r90,return180d:r180,relative30d:br30==null?null:r30-br30,relative90d:br90==null?null:r90-br90,drawdown90d:dd90,distance50d:dist50,distance200d:dist200,pattern,extended,constructive,pullback}}


function ema(vals,n){if(vals.length<n)return null;const k=2/(n+1);let e=avg(vals.slice(0,n));for(let i=n;i<vals.length;i++)e=vals[i]*k+e*(1-k);return e}
function weeklyCloses(prices){const out=[];for(const row of prices||[]){if(!Array.isArray(row)||!Number.isFinite(row[1]))continue;const d=new Date(row[0]),day=(d.getUTCDay()+6)%7,start=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()-day);if(!out.length||out.at(-1).week!==start)out.push({week:start,t:row[0],close:row[1]});else out[out.length-1]={week:start,t:row[0],close:row[1]}}return out}
function linreg(vals){if(vals.length<2)return null;const n=vals.length,mx=(n-1)/2,my=avg(vals);let a=0,b=0;for(let i=0;i<n;i++){a+=(i-mx)*(vals[i]-my);b+=(i-mx)**2}return b?a/b:null}
function structuralState(prices,pa){
 const rows=(prices||[]).filter(x=>Array.isArray(x)&&Number.isFinite(x[1])),vals=rows.map(x=>x[1]);if(vals.length<210)return null;
 const last=vals.at(-1),weeks=weeklyCloses(rows),now=new Date(),todayDay=(now.getUTCDay()+6)%7,currentWeek=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-todayDay),completedWeeks=weeks.filter(x=>x.week<currentWeek),weekly=completedWeeks.map(x=>x.close),ema200=ema(vals,200),oldEma=vals.length>=220?ema(vals.slice(0,-20),200):null,emaSlope=ema200&&oldEma?(ema200/oldEma-1)*100:null;
 const prior=weekly.slice(-54,-2),recent26=prior.slice(-26),resistance=recent26.length?Math.max(...recent26):null,longResistance=prior.length?Math.max(...prior):null;
 const consecutive=resistance?(()=>{let n=0;for(let i=weekly.length-1;i>=0&&weekly[i]>resistance;i--)n++;return n})():0,distanceResistance=resistance?ret(resistance,last):null,above200=ema200?last>ema200:null,trendSlope=linreg(vals.slice(-120).map(v=>Math.log(v)))*120*100,broke=resistance&&last>resistance,near=resistance&&distanceResistance>=-8&&distanceResistance<=3,retest=broke&&distanceResistance<=8&&distanceResistance>=0&&consecutive>=1,extended=pa?.extended||(distanceResistance!=null&&distanceResistance>22);
 let stage="BELOW STRUCTURAL RESISTANCE";if(extended&&broke)stage="EXTENDED";else if(retest&&consecutive>=2)stage="SUPPORT HELD";else if(retest)stage="RETEST / HOLD";else if(broke&&consecutive>=2)stage="CONFIRMED BREAKOUT";else if(broke)stage="BREAKOUT ATTEMPT";else if(near)stage="NEAR BREAKOUT";else if(above200&&trendSlope>0)stage="EARLY STRUCTURE";
 return{stage,resistance,longResistance,distanceResistance,ema200,above200,ema200Slope20d:emaSlope,weeklyConfirmation:consecutive>=2?"CONFIRMED":consecutive===1?"ONE WEEK CLOSE":"UNCONFIRMED",consecutiveWeeklyClosesAbove:consecutive,trendSlope120d:trendSlope,note:"Structural levels are derived from prior weekly closes and the 200-day EMA. They are market-structure references, not price targets or valuation evidence."}}
function btcDownsideSensitivity(prices,btc){
 const a=(prices||[]).filter(x=>Array.isArray(x)&&Number.isFinite(x[1])),b=(btc||[]).filter(x=>Array.isArray(x)&&Number.isFinite(x[1]));if(a.length<100||b.length<100)return null;
 const am=new Map(a.map(x=>[new Date(x[0]).toISOString().slice(0,10),x[1]])),bm=new Map(b.map(x=>[new Date(x[0]).toISOString().slice(0,10),x[1]])),dates=[...bm.keys()].filter(d=>am.has(d)).sort(),events=[];
 for(let i=7;i<dates.length;i++){const d0=dates[i-7],d1=dates[i],br=ret(bm.get(d0),bm.get(d1));if(br!=null&&br<=-5){const ar=ret(am.get(d0),am.get(d1));if(ar!=null)events.push({date:d1,btcReturn:br,assetReturn:ar,beta:br!==0?ar/br:null})}}
 const picked=[];for(const e of events){const prev=picked.at(-1);if(!prev||new Date(e.date)-new Date(prev.date)>14*864e5)picked.push(e);else if(e.btcReturn<prev.btcReturn)picked[picked.length-1]=e}
 const recent=picked.slice(-8),betas=recent.map(x=>x.beta).filter(Number.isFinite),downsideBeta=avg(betas),assetAvg=avg(recent.map(x=>x.assetReturn)),btcAvg=avg(recent.map(x=>x.btcReturn));let state="INSUFFICIENT EVENTS";if(recent.length>=2)state=downsideBeta>1.5?"HIGH DOWNSIDE SENSITIVITY":downsideBeta>1?"ABOVE-BTC DOWNSIDE":downsideBeta>=0.6?"MODERATE DOWNSIDE":"DEFENSIVE VS BTC";
 return{state,downsideBeta,eventCount:recent.length,averageAssetReturn:assetAvg,averageBtcReturn:btcAvg,events:recent.slice(-5),note:"Observed from non-overlapping 7-day windows where BTC fell at least 5%. Historical downside sensitivity is descriptive and may change in future regimes."}}

function chartSeries(prices){const rows=(prices||[]).filter(x=>Array.isArray(x)&&Number.isFinite(x[1])),vals=rows.map(x=>x[1]);return rows.map((x,i)=>{const roll=n=>i+1>=n?avg(vals.slice(i+1-n,i+1)):null;return{t:x[0],price:x[1],ma50:roll(50),ma200:roll(200)}})}
function familyMap(ps){const g=new Map();for(const p of ps||[]){const k=String(p?.parentProtocol||"");if(k.startsWith("parent#")&&num(p.tvl)>0){if(!g.has(k))g.set(k,[]);g.get(k).push(p)}}return g}
function weightedChange(rows){let tvl=0,old=0,ok=0;for(const p of rows||[]){const t=num(p.tvl),c=num(p.change_7d);if(!(t>0)||c==null||c<=-99)continue;tvl+=t;old+=t/(1+c/100);ok++}return ok&&old>0?(tvl/old-1)*100:null}
export default async function handler(req,res){try{
 const id=String(req.query.id||"").trim();if(!/^[a-z0-9-]{1,100}$/i.test(id))return res.status(400).json({error:"invalid id"});
 const h=headers();
 // One browser endpoint supplies both price-action and research-intelligence panels.
 // The asset's 365D history is fetched once instead of separately by two endpoints.
 const [coin,trending,hist,btc,protocols]=await Promise.all([
  j(`${CG}/coins/${encodeURIComponent(id)}?localization=false&tickers=false&market_data=false&community_data=false&developer_data=false&sparkline=false`,h),
  j(`${CG}/search/trending`,h),
  j(`${CG}/coins/${encodeURIComponent(id)}/market_chart?vs_currency=usd&days=365&interval=daily`,h),
  j(`${CG}/coins/bitcoin/market_chart?vs_currency=usd&days=365&interval=daily`,h),
  j("https://api.llama.fi/protocols")
 ]);
 if(!hist?.prices?.length)return res.status(502).json({error:"asset history unavailable"});
 const priceAction=stats(hist.prices||[],btc?.prices||[]),priceHistory=chartSeries(hist.prices||[]),structure=structuralState(hist.prices||[],priceAction),btcDownside=btcDownsideSensitivity(hist.prices||[],btc?.prices||[]);
 const trendCoins=(trending?.coins||[]).map((x,i)=>({id:x?.item?.id,rank:i+1})),tr=trendCoins.find(x=>x.id===id),cats=(coin?.categories||[]).filter(Boolean).slice(0,6);
 const vols=(hist?.total_volumes||[]).map(x=>num(x[1])).filter(x=>x!=null),recent=avg(vols.slice(-7)),prior=avg(vols.slice(-14,-7)),volumeAcceleration=recent!=null&&prior>0?(recent/prior-1)*100:null;
 let attention=35,attentionObserved=0;if(tr){attention+=Math.max(10,35-tr.rank*3);attentionObserved++}if(volumeAcceleration!=null){attention+=volumeAcceleration>50?25:volumeAcceleration>20?15:volumeAcceleration>0?7:volumeAcceleration<-30?-10:0;attentionObserved++}
 attention=Math.round(clamp(attention,0,100));const attentionCoverage=Math.round(attentionObserved/2*100);
 let competitive={status:"NOT MATCHED",category:null,marketShare:null,projectTvl7d:null,sectorTvl7d:null,relativeMomentum:null};
 if(Array.isArray(protocols)){const fam=familyMap(protocols),children=[];for(const p of protocols){if(p?.gecko_id===id&&p.parentProtocol&&fam.has(p.parentProtocol)){children.push(...fam.get(p.parentProtocol));break}else if(p?.gecko_id===id)children.push(p)}if(children.length){const category=children.find(x=>x.category)?.category||null,projectTvl=children.reduce((s,x)=>s+(num(x.tvl)||0),0),projectTvl7d=weightedChange(children),sector=(protocols||[]).filter(x=>x.category===category&&num(x.tvl)>0),sectorTvl=sector.reduce((s,x)=>s+(num(x.tvl)||0),0),sectorTvl7d=weightedChange(sector);competitive={status:"OBSERVED",category,marketShare:sectorTvl>0?projectTvl/sectorTvl*100:null,projectTvl7d,sectorTvl7d,relativeMomentum:projectTvl7d!=null&&sectorTvl7d!=null?projectTvl7d-sectorTvl7d:null}}}
 const narrativeState=tr?"TRENDING / HIGH ATTENTION":volumeAcceleration!=null&&volumeAcceleration>25?"ATTENTION ACCELERATING":volumeAcceleration!=null&&volumeAcceleration<-25?"ATTENTION COOLING":"NO STRONG ATTENTION SIGNAL";
 res.setHeader("Cache-Control","s-maxage=900, stale-while-revalidate=1800");
 return res.status(200).json({id,priceAction,priceHistory,structure,btcDownside,categories:cats,narrative:{state:narrativeState,attentionScore:attention,coverage:attentionCoverage,trendingRank:tr?.rank??null,volumeAcceleration7dVsPrior7d:volumeAcceleration,note:"Attention is observational, not a thesis or buy score. Trending presence and trading-volume acceleration are proxies, not proof of durable capital inflow."},competitive,catalystQuality:{status:"PENDING VERIFIED SOURCE INGESTION",note:"Catalyst quality is not inferred from unsourced headlines."},coinGeckoDemoKey:!!process.env.COINGECKO_DEMO_API_KEY,at:new Date().toISOString()});
}catch(e){return res.status(502).json({error:"research context unavailable"})}}
