function avg(a,n){if(!a||a.length<n)return null;return a.slice(-n).reduce((s,x)=>s+x,0)/n}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function series(id){let r=await fetch(`https://api.coingecko.com/api/v3/coins/${id}/market_chart?vs_currency=usd&days=210&interval=daily`,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(String(r.status));let j=await r.json();return (j.prices||[]).map(x=>x[1]).filter(Number.isFinite)}
async function one(id,btc30){try{let p=await series(id),last=p.at(-1),ma50=avg(p,50),ma200=avg(p,200),r30=p.length>30?(last/p.at(-31)-1)*100:null,trend=ma50&&ma200?(last>ma50&&ma50>ma200?"Above 50D / 200D":last<ma50&&ma50<ma200?"Below 50D / 200D":"Mixed"):"Insufficient history";return[id,{price:last,ma50,ma200,return30d:r30,relative30d:r30!=null&&btc30!=null?r30-btc30:null,trend}]}catch(e){return[id,{error:"upstream unavailable",price:null,ma50:null,ma200:null,return30d:null,relative30d:null,trend:null}]}}
export default async function handler(req,res){try{
 let ids=[...new Set(String(req.query.ids||"").split(",").map(x=>x.replace(/[^a-z0-9_-]/gi,"")).filter(Boolean).slice(0,12))];
 let btc=await series("bitcoin"),btc30=btc.length>30?(btc.at(-1)/btc.at(-31)-1)*100:null,pairs=[];
 for(let i=0;i<ids.length;i+=2){let batch=ids.slice(i,i+2);pairs.push(...await Promise.all(batch.map(id=>id==="bitcoin"?Promise.resolve(["bitcoin",{price:btc.at(-1),ma50:avg(btc,50),ma200:avg(btc,200),return30d:btc30,relative30d:0,trend:btc.at(-1)>avg(btc,50)&&avg(btc,50)>avg(btc,200)?"Above 50D / 200D":btc.at(-1)<avg(btc,50)&&avg(btc,50)<avg(btc,200)?"Below 50D / 200D":"Mixed"}]):one(id,btc30))));if(i+2<ids.length)await sleep(350)}
 res.setHeader("Cache-Control","s-maxage=1800, stale-while-revalidate=3600");res.status(200).json(Object.fromEntries(pairs))
}catch{res.status(502).json({error:"trend feed unavailable"})}}